### ISSUE TITLE
Network.enable is required Network.setUserAgentOverride 

### ISSUE THREAD

**Issue by paulirish** [ChromeDevTools/devtools-protocol#10]
This is unlike every other method, so it should probably be fixed.

In the short term it would be ideal if an error was returned on `Network.setUserAgentOverride` communicating `enable()` wasn't called yet.

**Comment by tomasdev** [comment]
Hey Paul, I don't know if this is a bug or I'm not fully understanding the method:

```js
function onPageLoad(Runtime) {
  return Runtime.evaluate({expression: "navigator.userAgent"}).then(result => console.log('UA: ' + result.result.value));
}
launchChrome().then(launcher => {
  chrome(protocol => {
    const {Page, Runtime, Network} = protocol;
    Promise.all([
      Page.enable(),
      Runtime.enable(),
      Network.enable()
    ]).then(() => {
      Network.setUserAgentOverride('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36');
      Page.navigate({url: 'https://google.com/'});
      Page.loadEventFired(() => {
        onPageLoad(Runtime).then(() => console.log('done'));
      });
      // ...
```
is printing HeadlessChrome as the UA :/

**Comment by gsouf** [comment]
Agreed, spent time trying to figure out why Network.setUserAgentOverride didn't work, would be great to have a fix

**Comment by coder77** [comment]
Is this issue still open?
await cdp.send(`Network.setUserAgentOverride({userAgent:"${config.userAgent}"})`);
still cannot

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
