### ISSUE TITLE
multiple copies of protocol_json are exported in npm package

### ISSUE THREAD

**Issue by nojvek** [ChromeDevTools/devtools-protocol#100]
![image](https://user-images.githubusercontent.com/1018196/39535180-1fc158f6-4de8-11e8-9ba3-ee7eb7abf574.png)

Should the pdl files also include the .json files again? seems a waste of network bandwidth

you can use [package.json 'files' directive](https://docs.npmjs.com/files/package.json#files) to only export directories that are needed

**Comment by paulirish** [comment]
thx for filing. An npm release snuck out with this but I believe it's been fixed. 
I'll doublecheck.

**Comment by paulirish** [comment]
@nojvek funky behavior in the conversion script: https://chromium.googlesource.com/deps/inspector_protocol/+/master/convert_protocol_to_json.py#23

this script is used in v8's repo, node.js's repo, and chromium's repo so there's a lot of back-compat behavior. anyway! sorted now.

thx for reporting!
