### ISSUE TITLE
Setting offline=true via Network.emulateNetworkConditions does not stop serviceworkers from going online

### ISSUE THREAD

**Issue by ldiary** [ChromeDevTools/devtools-protocol#102]
When using the Network.emulateNetworkConditions to make the browser simulate offline mode, web applications that use serviceworkers are still able to bypass this setting and connect online. Therefore, this offline setting is not suitable to test the offline behaviour of these serviceworkers.

I am using the PyChromeDevTools:
```
    import PyChromeDevTools
    chrome = PyChromeDevTools.ChromeInterface()
    chrome.Network.emulateNetworkConditions(offline=True, latency=250, downloadThroughput=270, uploadThroughput=300)
```

I tried Puppeteer and WebDriverJS as well, using setNetworkConditions(), however the outcome is the same - serviceworkers bypass the offline setting and connects online.

The only thing that works is when you manually open Chrome DevTools, go to Network and tick the Offline box - this definitely stops all serviceworkers from connecting online.

**Comment by paulirish** [comment]
True. The service worker is it's own target. 

so you'll need to send the same `Network.emulateNetworkConditions` call to that target. Via protocol monitor in devtools, you can see how it's done. 

![image](https://user-images.githubusercontent.com/39191/40384877-b2e4fcec-5db9-11e8-9c16-c9e7ee268712.png)

Message passed to SW target via `Target.sendMessageToTarget`

**Comment by paulirish** [comment]
I'll add that dealing with subtargets is kinda painful. :)  So good luck.

Here's something to help: https://github.com/cyrus-and/chrome-remote-interface/wiki/Inspect-subtargets-like-a-service-worker

**Comment by ldiary** [comment]
Thanks for the response! 
What version of Chrome has this Protocol Monitor?
I can't seem to find an option for Protocol Monitor in "More Tools" even in Canary version.

**Comment by ldiary** [comment]
I managed to get ahold of Protocol Monitor by cloning the DevTools FrontEnd repo.
I just need one more help though, if you have time to spare.
Any hint on how I can get the sessionId of the subtarget, please?

```
>>> Target.getTargets()
...
{ targetInfos: 
   [ { targetId: '297205B0732F47F63723147667C3EB11',
       type: 'service_worker',
       title: 'Service Worker https://staging.com',
       url: 'https://staging.com',
       attached: false },
     { targetId: '5C73186AE57FE38039B3BD3A5A6C0FA3',
       type: 'page',
       title: 'My Awesome App',
       url: 'https://staging.com/awesome',
       attached: true } ] }
>>> Target.getTargetInfo({targetId: '297205B0732F47F63723147667C3EB11'});
...
{ targetInfo: 
   { targetId: '297205B0732F47F63723147667C3EB11',
     type: 'service_worker',
     title: 'Service Worker https://staging.com',
     url: 'https://staging.com',
     attached: false } }
>>> Target.attachToTarget({targetId: '297205B0732F47F63723147667C3EB11'})
...
{ sessionId: '297205B0732F47F63723147667C3EB11:1' }
```
Above, I managed to get the sessionId of the ServiceWorker, but I still can't figure out how to get the sessionId or targetId of its subtarget - the dedicated worker.

**Comment by paulirish** [comment]
> What version of Chrome has this Protocol Monitor?

It's in Canary and probably beta, though probably not stable.
Have to turn on DevTools experiments first. https://hackernoon.com/hidden-experimental-features-in-chrome-devtools-2ae93b11b628

See: https://umaar.com/dev-tips/166-protocol-monitor/  


----------------


> Any hint on how I can get the sessionId of the subtarget, please?

there's two options:

1. `Target.setAutoAttach({autoAttach:true})` like the wiki page says. you'll then get an event of related targets. and in there is a session ID. service workers are usually considered "related", but it's possible that this won't fire, based on the SW process model.
1. after your `Target.getTargets()` response, you can then call `Target.attachToTarget` with the targetID you have. In the response you get a session ID. https://chromedevtools.github.io/devtools-protocol/tot/Target#method-attachToTarget


Good luck!

**Comment by ldiary** [comment]
Thanks a lot for all the help!
I finally managed to simulate offline mode for serviceworkers.
https://github.com/ldiary/marigoso/blob/master/notebooks/how-to-simulate-offline-browsing-for-serviceworker-testing-using-selenium-webdriver-and-chrome-devtools.ipynb
