### ISSUE TITLE
Typescript events

### ISSUE THREAD

**Issue by ameola** [ChromeDevTools/devtools-protocol#104]
Thanks for the TSD work. It works well but I'm having some problems understanding how events are intended to operation. I'm using chrome-remote-interface to setup the connection. I have been following the conversation in #90 

I'm not sure I'm understanding how events are intended to function. What actually fires the event? Is it intended that we use untyped versions of the interface to hook up the events and then fire them through the node.js event emitter? It would be great if we could get an example of the intended usage.

The specific example I'm looking at is the page.loadEventFired event. For now, I'm doing this:
```
            (this.Page as any).loadEventFired(() => {
                this.handlePageLoad(blah);
            });
```

**Comment by brendankenny** [comment]
`chrome-remote-interface` has its own API it generates from the protocol, so I believe you won't have much luck using the current `protocol.d.ts` for types of *functions* for listening for events, sending commands, etc. That's all the function signatures under `PageApi`, `SecurityApi`, etc.

It *does* look like `await Page.loadEventFired()` will work for you, but that API doesn't have anything to do with the raw protocol. That's provided by `chrome-remote-interface`.

However you can use some of the types for the *payloads* received from those events, commands, etc. e.g.
```
Page.on('loadEventFired', loadEventFiredEvent => {
    // do something with loadEventFiredEvent.timestamp
});
```

and `loadEventFiredEvent` will be of type [`Page.LoadEventFiredEvent`](https://github.com/ChromeDevTools/devtools-protocol/blob/5fd68597ad779a828c438f2a6cc5f5853a701603/types/protocol.d.ts#L12650-L12652)

Looking at the types provided in `protocol.d.ts`, I think there are more type primitives we can provide for easier typing of libraries using the devtools protocol. We'll investigate that, but typing of libraries like `chrome-remote-interface` will still have to build on those in their own repos (or in DefinitelyTyped).

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
