### ISSUE TITLE
CSS.getMatchedStylesForNode does not specify how styles are cascaded

### ISSUE THREAD

**Issue by robpaveza** [ChromeDevTools/devtools-protocol#109]
...unless the ordering of the matched rules returned is significant.  From inspecting protocol requests - e.g., for https://codepen.io/anon/pen/rrNEam - it appears that the order of styles returned would be teal, yellow, blue, gray.  This is the inverse of the way the styles appear in DevTools. 

This seems consistent for the Styles cascade as well as the computed styles list.

Should we expect that order is therefore significant in the way it's transmitted?

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
