### ISSUE TITLE
Log domain APIs only fetch log entries with network as the source. 

### ISSUE THREAD

**Issue by goelayu** [ChromeDevTools/devtools-protocol#111]
As described [here](https://chromedevtools.github.io/devtools-protocol/tot/Log#event-entryAdded) , the log.entryAdded event is called for every log entry. These log entries could be generated from a bunch of sources (source.xml, javascript, network, storage, appcache, rendering, security, deprecation, worker, violation, intervention, recommendation, other). However on using the API I can only receive the log entries for entries with 'Network' as the source. All the other events aren't received by my event handler. 

Is this the correct behavior? Is there a way to enable log entries from other sources by default?

**Comment by goelayu** [comment]
Update: I see there are other APIs available to fetch logs from different kind of sources.
For example for javascript exceptions, there is the event Runtime.exceptionThrown and for the console API, there is the event Runtime.consoleAPIcalled. 
Even though these APIs do server the purpose, shouldn't the Log domain's entryAdded event take care of all these?
@paulirish

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
