### ISSUE TITLE
TargetInfo has two fields(url and title) with same value

### ISSUE THREAD

**Issue by NivedhaSenthil** [ChromeDevTools/devtools-protocol#112]
The targetInfo that we get on targetCreated or targetInfoChanged  event has two fields url and title with same value most of the times but sometimes it is actually the page title. Shouldn't the title be title of the target inspite of url all the time ? 

Sample targetInfo received with 'url' and 'title' having same value,

```
{ targetInfo:
   { targetId: 'C1BEA709C7470F3A165331B2F1D1F480',
     type: 'page',
     title: 'https://www.google.com',
     url: 'https://www.google.com/',
     attached: true,
     browserContextId: 'FDDB225D367F22D11CBFCAFFAA55D91C' } }
```

**Comment by JoelEinbinder** [comment]
This is likely because you get the targetcreated before the page has finished loading. So the title tag has not been read yet.

**Comment by NivedhaSenthil** [comment]
Thanks for the quick response, doing `getTargets()` after page load gives right title always.
