### ISSUE TITLE
shift key + left mouse click

### ISSUE THREAD

**Issue by 4ydx** [ChromeDevTools/devtools-protocol#115]
When using Input.dispatchKeyEvent, what parameters aside from modifier and type do I need to pass in order to indicate that I want a modifier key to be held down?  I am trying to emulate "shift + left mouse click".  Mouse clicking itself is clearly working, but shift doesn't seem to be.

Type: "keyDown"
Modifier : 8

**Comment by JoelEinbinder** [comment]
You need to pass the same modifiers flag into the dispatchMouseEvent.

**Comment by 4ydx** [comment]
Ok I see that now.  Much appreciated.

**Comment by 4ydx** [comment]
I'm not sure what the issue is, but the shift just doesn't seem to be registering in the browser.

I am sending the dispatchKeyEvent first with the shift modifier followed by the Input.dispatchMouseEvent.  Do I have to pass something other than just Type and Modifiers in the dispatchKeyEvent?  Is that event even required?

**Comment by 4ydx** [comment]
Ok by adding the following, which is the value for shift, to the Input.dispatchKeyEvent, I am now seeing that the shift is being registered during the mouse event.  

WindowsVirtualKeyCode: 16

It appears that I do not have to pass the Modifiers value to Input.dispatchMouseEvent at all.
