### ISSUE TITLE
Memory or disk cache?

### ISSUE THREAD

**Issue by iadolgov** [ChromeDevTools/devtools-protocol#116]
Hello. Is there a way to understand what type of cache was used for response - memory or disk?

**Comment by codesorter2015** [comment]
Please check with response.fromCache() method
True if the response was served from either the browser's disk cache or memory cache.

**Comment by iadolgov** [comment]
I need to understand: from which cache?: browser's disk cache or memory cache?

**Comment by JoelEinbinder** [comment]
You can use `fromDiskCache` on Network.Response to see if it was from the disk cache.

**Comment by iadolgov** [comment]
There are two types of "disk cache": memory cache and disk cache
![image](https://user-images.githubusercontent.com/33341875/52399770-3a39b200-2ace-11e9-82cc-f121f66d2bdf.png)

**Comment by iadolgov** [comment]
I found a solution. Thanks to all.
