### ISSUE TITLE
Is there a way to get the raw bytes of a response?

### ISSUE THREAD

**Issue by molant** [ChromeDevTools/devtools-protocol#12]
For example, if the content is gzipped is there any way I can access the raw bytes? [getResponseBody](https://chromedevtools.github.io/debugger-protocol-viewer/tot/Network/#method-getResponseBody) only seems to return a string and other events like `dataReceived`, etc. don't seem to have that data :(

**Comment by ui4j** [comment]
You should first listen **Network.responseReceived** event to find **requestId** and then invoke **Network.getResponseBody** command to get response body.

If you need Java based solution, please review this [sample](https://github.com/webfolderio/cdp4j/blob/master/src/test/java/io/webfolder/cdp/sample/NetworkResponse.java) code.

**Comment by molant** [comment]
Thanks @ui4j, but unfortunately this isn't exactly what I need.
Whenever I do a `Network.getResonseBody` I get the body text, not the original compressed bytes (if they were compressed).
Also when the response isn't text (like images) I get the following response (which is not very useful):
```json
{
  "body": "",
  "base64Encoded": true
}
```
I'm using [chrome remote interface](https://github.com/cyrus-and/chrome-remote-interface/) but it doesn't seem to be a problem with it :(

**Comment by paulirish** [comment]
AFAIK we don't have support for this now and no immediate plans to implement. cc @allada 
Network responses are decoded in the Chromium /net layer a bit earlier than our instrumentation starts, so it's some effort to get the data.

Also unimplemented, but if the protocol exposed a way to set a proxy, then you could run a network proxy to grab these bytes. In the future, it's possible a `.setProxy()` method might surface, though I've only seen [this person mention working on it](https://groups.google.com/a/chromium.org/d/topic/headless-dev/YP3fhONROmU/discussion).  ¯\\_(ツ)_/¯
