### ISSUE TITLE
Question about DOM.setAttributeValue

### ISSUE THREAD

**Issue by 4ydx** [ChromeDevTools/devtools-protocol#120]
Does DOM.setAttributeValue allow one to edit an input's value so that the new value will be displayed in the browser?  Or is the only way to interact with an input to either evaluate javascript or focus on the element and perform keystrokes?

I am seeing that DOM.setAttributeValue does not trigger a visual change in the input when changing the "value" attribute.

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
