### ISSUE TITLE
Is there an extended documentation for Tracing Domain?

### ISSUE THREAD

**Issue by AshDee** [ChromeDevTools/devtools-protocol#121]
I have been working with the `tracing` domain for the past two days and have logged the results to console.
Is there a documentation which can give some ideas on the different categories and the names that come in the tracing result.

Would be great to know what they represent.

**Comment by JoelEinbinder** [comment]
You can check out `chrome://tracing/` to try to find some clues. But unfortunately there isn't extensive documentation on all of the categories.

**Comment by patrickhulce** [comment]
@AshDee you might find this [document](https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview) helpful on deciphering trace events.

**Comment by AshDee** [comment]
Thanks a lot, @patrickhulce , @JoelEinbinder
