### ISSUE TITLE
Paint order in Domsnapshot deprecated

### ISSUE THREAD

**Issue by mstaros** [ChromeDevTools/devtools-protocol#123]
Method DOMSnapshot.getSnapshot is deprecated , and hence  there is no way(or very complex one) to get paint order of dom nodes. Will  it be  added to DOMSnapshot.captureSnapshot later on?

**Comment by elipskiy** [comment]
Up

**Comment by kicktheken** [comment]
`paintOrders` is documented [here](https://chromedevtools.github.io/devtools-protocol/tot/DOMSnapshot#type-LayoutTreeSnapshot) for `DOMSnapshot.captureSnapshot` but it does not seem to be working:

```javascript
const puppeteer = require('puppeteer');

(async () => {
  const puppeteerOptions = { headless: true, ignoreHTTPSErrors: true };
  const browser = await puppeteer.launch(puppeteerOptions);

  console.log('browser version', await browser.version());

  const page = await browser.newPage();
  const client = await page.target().createCDPSession();

  await page.goto('https://www.google.com');

  const { documents } = await client.send('DOMSnapshot.captureSnapshot', { computedStyles: [], includePaintOrder: true });

  const [ document ] = documents;
  const { layout } = document;

  // this is missing paintOrders key
  console.log('layout keys', Object.keys(layout));

  if (puppeteerOptions.headless) {
    await browser.close();
  }
})();
```

logs:
```
browser version HeadlessChrome/78.0.3882.0
layout keys [ 'nodeIndex', 'styles', 'bounds', 'text', 'stackingContexts' ]
```

Anyone know the status of this issue?

**Comment by bmeurer** [comment]
Please file a devtools bug at https://crbug.com

**Comment by kicktheken** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1013033

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
