### ISSUE TITLE
DevTools for Node no longer has "Network" source for source files

### ISSUE THREAD

**Issue by brucejo75** [ChromeDevTools/devtools-protocol#126]
I did not notice when this changed because I have been working around #103, by using an older version of devTools.

The source navigator used to have a "Network" tab.  I have a scenario where just using Filesystem does not work and I am requesting bringing back the "Network" tab or providing a solution for my scenario.

### Environment
**Windows 10**: Version 1803 (OS Build 17134.345)
**node**: 8.11.3 (using WSL: Windows Subsystem for Linux, essentially Ubuntu)
**chrome**: 69.0.3497.100 & 72.0.3580.0 (Official Build) canary (64-bit)

### node script index.js:
```javascript
1 let foo = require('./foo');
2 console.log('hello World');
3 foo();
```
### node script foo.js
```javascript
1 function foo() {
2   console.log('Hit 1?');
3   debugger;
4   console.log('Hit 2?');
5 }
6
7 module.exports = foo;
```
### Debugging Scenario
1. open a bash command shell in WSL
2. run `node --inspect-brk index.js`
3. add folder to my workspace `E:\issue`
4. find and open `foo.js`.
5. set a breakpoint in `foo.js` line 2.
6. in devTools, resume script execution (e.g. hit `F8`)

Result: breakpoint in `E:\issue\foo.js` is not hit, devTools stops on `debugger;` statement in `/mnt/e/issue/foo.js`.

### Observations
- Running chrome on Windows.  DevTools is running within Windows so Filesystem uses windows file path (`E:\issue`).
- Running `node` on Ubuntu using WSL.  Files are referenced using Ubuntu file path. (`/mnt/e/issue`).
- devTools is able to find and display the Ubuntu file path files when they hit the `debugger;` statement
- I can workaround this by using NIM and an old version of the devTools, which still has the Network tab.  After `foo.js` has been required, I can see the file in the network tab.
### Options
1. Bring back the Network tab.
2. Add the ability to navigate the Ubuntu file system on Windows WSL.
3. And unfortunately, decline to do anything because it is viewed as an edge case.
please help?  :grin:

**Comment by brucejo75** [comment]
Also, if you can point me to some code and a suggested change, I might be able to pull together a pull request.

**Comment by june07** [comment]
As you stated and in the case of option 3... using an older version of DevTools via NiM is a viable solution.

Also node, you can choose whatever version of DevTools suites your use case...

See the following for how to do that:

https://june07.com/blog/nim-custom-devtools-url

**Comment by brucejo75** [comment]
Oops.  this works for me.  I had failed to put in the correct route to my filesystem.  Yay!
