### ISSUE TITLE
Breakpoint on native method

### ISSUE THREAD

**Issue by 3asm** [ChromeDevTools/devtools-protocol#127]
Does the Chrome Devtools protocol have support for setting breakpoint on Window and Document native methods, like window.eval and document.getElementsByName?

**Comment by ak239** [comment]
There is no method, but it is possible by using command line API:
```
await Runtime.evaluate({
  expression: 'debug(Array.prototype.map, "arguments[0]"/* condition */)',
  includeCommandLineAPI: true
});
```

We actually should introduce method here, command line API method should just send another Runtime.inspectRequested event and our frontend should use new method to set breakpoint.

**Comment by 3asm** [comment]
Thanks for the tip. That's very helpful.
