### ISSUE TITLE
Network.requestIntercepted should include requestId

### ISSUE THREAD

**Issue by hofmeister** [ChromeDevTools/devtools-protocol#129]
The event payload from ```Network.requestIntercepted``` should really include the ```requestId```. 

I see the Puppeteer project is also doing some fairly hacky workarounds to identify the ```requestId``` for an intercepted request ( hashing the request in ```Network.requestWillBeSent``` and then matching that hash against the request received in ```Network.requestIntercepted``` - which is error prone at best since 2 identical request could be confused with one-another )

The work around above does work but having this built-in would likely reduce errors and make direct CDP use more straight forward.

**Comment by dgozman** [comment]
That's true indeed. We have a plan to address this. Unfortunately, it's not that easy technically, so it takes some time.

**Comment by aslushnikov** [comment]
for the record: downstream puppeteer issue regarding this - https://github.com/GoogleChrome/puppeteer/issues/3471

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
