### ISSUE TITLE
Input.dispatchMouseEvent interfering with cursor position

### ISSUE THREAD

**Issue by NivedhaSenthil** [ChromeDevTools/devtools-protocol#130]
Trying to simulate drag and drop using CDP's mouse events, dragging and dropping non HTML5 draggable elements works fine using mouse events like (move, press, move and release) whereas the same does not work properly with HTML5 draggable elements. The element is moving to the current cursor position instead of position given in `Input.dispatchMouseEvent`.

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
