### ISSUE TITLE
Accessibility.getFullAXTree not found (panel context)

### ISSUE THREAD

**Issue by AutoSponge** [ChromeDevTools/devtools-protocol#132]
Using latest Chromium and TOT.

When using `Accessibility.getFullAXTree` in the content context, it works as expected. However, when used in an extension panel context (devtools target), I get the following error.

`message: 'Protocol error (Accessibility.getFullAXTree): \'Accessibility.getFullAXTree\' wasn\'t found'`

Other commands, such as `DOM.getDocument` work as expected in this context.

Can this command, `Accessibility.getFullAXTree`,  be added to a devtools context?

EDIT: Could this be a permissions issue in the manifest?

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
