### ISSUE TITLE
Using The SystemInfo Domain methods and API's throws Protocol error (SystemInfo.getInfo): 'SystemInfo.getInfo' wasn't found

### ISSUE THREAD

**Issue by ramprasathdgl** [ChromeDevTools/devtools-protocol#133]
Using The SystemInfo Domain methods and API's throws error `Error: Protocol error (SystemInfo.getInfo): 'SystemInfo.getInfo' wasn't found`

Chromium browser version 
{
   "Browser": "Chrome/72.0.3617.0",
   "Protocol-Version": "1.3",
   "User-Agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3617.0 Safari/537.36",
   "V8-Version": "7.2.391",
   "WebKit-Version": "537.36 (@99a174b7b1d13e53dbb2cd3aab84ba589c862d86)",
}

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
