### ISSUE TITLE
Page.captureScreenshot not working on Mobile Safari iOS

### ISSUE THREAD

**Issue by aliimran** [ChromeDevTools/devtools-protocol#134]
I am trying to get a screenshot of a webpage from mobile safari for iOS, and I am getting following error when I execute Page.captureScreenshot command.

{"error":{"code":-32601,"message":"'Page.captureScreenshot' was not found","data":[{"code":-32601,"message":"'Page.captureScreenshot' was not found"}]},"id":1}

**Comment by JoelEinbinder** [comment]
iOS does not use the Chrome DevTools protocol.

**Comment by auchenberg** [comment]
@aliimran See https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/
