### ISSUE TITLE
Stop a loading request via requestId or interceptionId

### ISSUE THREAD

**Issue by cnicodeme** [ChromeDevTools/devtools-protocol#135]
Hi!

When you setup the setRequestInterception to True, you can define if you want to `continue` each subsequent requests, `respond` to them or `abort` them.

What I'm trying to achieve, is to `continue` them but later be able to `abort` them. This is currently not possible, or at least not via the `Network.continueInterceptedRequest` call.

The ideas behind this is simple: Being able to set a timeout for each sub-requests when loading a page.
The main URL has its own timeout, which is good, but I want to limit the resources (css, js, images, etc) to not take more than X seconds to be loaded.

That's why I thought about a way to abort a running request.

I tried with `Fetch.failRequest` but it doesn't work too.

An other alternative would be to set the timeout in the `continue` call for the given request, but I think having a way to stop running requests is better.

*FYI: I haven't found a way to do that, but maybe I missed something, I'm sorry if that's the case!*

**Comment by liushengqi000** [comment]
`      while(true){

            $time=date('r');

            echo "<script>parent.document.getElementById('context').innerText='{$time}';</script>";

            ob_flush();flush();

            sleep(2);

        }
`

em... i want to modify the HTTP responses in real time for a long connection

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
