### ISSUE TITLE
printToPDF - Japanese output in pdf with Chinese font

### ISSUE THREAD

**Issue by kingsleyarchibald** [ChromeDevTools/devtools-protocol#136]
printToPDF - Japanese output in pdf with Chinese font

Dear sir/ms,

I am trying to use the puppeteer nodejs module to convert html files with Japanese text in them into pdf format. Everything works, except that the outputted pdf file is in a Chinese font rather than Japanese. For most characters, it is hard to tell the difference, but one character for which the difference is clear is "直" (see attached files for how it is displayed in the Chinese font:
![chinese font](https://user-images.githubusercontent.com/45992158/50210576-d8a47380-03b9-11e9-9948-9e3a50133ebc.png)

I have tried debugging the issue in the puppeteer code, but it seems that they are simply calling Page.printToPDF(). When I use the headless: false option for puppeteer.launch(), I can see that the original html file displays the Japanese characters as expected, but the Chinese font is displayed in the output of the pdf() function. (the same is true for the screenshot() function)

puppeteer version: 1.11.0
nodejs version: v8.11.4
Windows 10 pro, x64

I apologize for troubling you if this is not the appropriate place to report this issues.

Best regards

**Comment by aslushnikov** [comment]
Hey @kingsleyarchibald,

The right place to file PDF issues is upstream to Chromium: https://crbug.com/new Chromium's PDF team might be able to help there.

I'll close this for now, but please feel free to post the link to the upstream bug here for the future reference.

**Comment by kingsleyarchibald** [comment]
thank you for the guidance aslushnikov

**Comment by kingsleyarchibald** [comment]
Here's the link: 
https://bugs.chromium.org/p/chromium/issues/detail?id=916816

They gave me a workaround, but seemed to think that the language setting was somehow getting lost when converting to a PDF with puppeteer.

Thanks again for you help
