### ISSUE TITLE
V8 Snapshot api

### ISSUE THREAD

**Issue by Banou26** [ChromeDevTools/devtools-protocol#137]
Would it be possible to expose a way of creating and reusing V8 snapshots through the devtools protocol ?
This could be very helpful when combined with puppeteer to shave off some initialization time.

**Comment by dgozman** [comment]
I think this would be hard to do because of different plumbing of snapshots
vs DevTools protocol. Also, V8 snapshots don't support
arbitrary-initialized worlds.

Thanks,
Dmitry

**Comment by Banou26** [comment]
Alright, thanks
