### ISSUE TITLE
Performance difference between sendMessageToTarget and one web socket per target

### ISSUE THREAD

**Issue by adtrevor** [ChromeDevTools/devtools-protocol#139]
Depending on how you use the protocol, you can either send a message directly to a target by referencing a session ID, or you could get a list of targets and make an individual web socket connection for each. I was wondering if the "one web socket per target" might benefit of (at least theoretically) better performance?

**Comment by dgozman** [comment]
That's a good question. We didn't compare performance of the two approaches, and have no data to share, unfortunately. Please share your results if you decide to experiment :)

**Comment by adtrevor** [comment]
@dgozman I will if I do! Thanks! :)
