### ISSUE TITLE
Intercepting Preflight request

### ISSUE THREAD

**Issue by NivedhaSenthil** [ChromeDevTools/devtools-protocol#140]
Trying to intercept request that triggers preflight request, found that event with request method OPTION only comes when listening on `requestIntercepted` not sure what is the best way to intercept and mock response for such requests. 
As a work around launching chrome with '--disable-web-security' arg so that preflight requests are not triggered and be able to mock the actual request.

Can someone help me find the best way to do it ?

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
