### ISSUE TITLE
Emulate devices using dev tools protocol 

### ISSUE THREAD

**Issue by goelayu** [ChromeDevTools/devtools-protocol#141]
I am trying to emulate a device ( let's say pixel 2) using the browser version of Chrome. 
The devtools protocol has an API `Page.setDeviceMetricsOverride` which is apparently depricated now. Is there any alternative API ? Or am I suppose to use individual command line flags like `--window-size` `--user-agent`  and `--use-mobile-user-agent`and manually set these values to correctly emulate an android browser running inside a mobile device.

**Comment by JoelEinbinder** [comment]
There is Emulation.setDeviceMetricsOverride

**Comment by goelayu** [comment]
And I suppose I'll have to use `Emulation.setUserAgentOverride` separately as well, to correctly emulate a mobile device setup.

**Comment by paulirish** [comment]
yup.

fwiw this is what lighthouse does: https://github.com/GoogleChrome/lighthouse/blob/ff41f6a289a3171ed0ec70c389de0181d8e59ca2/lighthouse-core/lib/emulation.js#L76-L80
