### ISSUE TITLE
Connect to Chrome's inspector's inspector using devtools protocol

### ISSUE THREAD

**Issue by goelayu** [ChromeDevTools/devtools-protocol#142]
According to [this](https://developers.google.com/web/updates/2015/07/who-inspects-the-inspector) you can inspect the Chrome's inspector itself. I am wondering if there is a way to connect to this window and be able to issue the devtool API calls, instead of issuing them to the main Chrome window.

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
