### ISSUE TITLE
Request interception does not work with Fetch...

### ISSUE THREAD

**Issue by leksito** [ChromeDevTools/devtools-protocol#143]
Hi

Sorry for my bad english.

I made proxy manager, that catches Fetch.requestPaused, then creates connection to some proxy, makes request and then makes Fetch.fullfilRequest.
I have crawler (it's other process), that needs to catch Network.requestIntercepted to get content. But when proxy manager works, crawler does not catch this event. If I kill proxy manager, then crawler catches all events. 

I have not found anything about it in documentation.

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
