### ISSUE TITLE
Browser Stops Responding for Several Seconds

### ISSUE THREAD

**Issue by pmurley** [ChromeDevTools/devtools-protocol#144]
I've been experiencing an issue where the browser (vanilla Chrome on OS X) stops sending any DevTools messages for 5-10 seconds in the middle of a page load. It happens on many different websites, and I'm really at a loss for how to debug further.

I'm attaching a protocol trace for a load of www.cnn.com. You can see (line 747-748) there's a 6 second delay in between messages. Sometimes it's longer/shorter, but I don't understand why it's happening. Would be grateful for any ideas.

[log.log](https://github.com/ChromeDevTools/devtools-protocol/files/2805523/log.log)

**Comment by JoelEinbinder** [comment]
What command line args are you launching chrome with?

**Comment by pmurley** [comment]
Flags I'm using:

--no-first-run
--no-default-browser-check
--incognito
--remote-debugging-port=9222

**Comment by JoelEinbinder** [comment]
Is your page on screen and the active tab the entire time? There is a lot of stuff in chrome about throttling and background tabs that are in the background or even just covered by other windows. You can look at Launcher.js in puppeteer to see the flags we use to suppress that behavior.

**Comment by pmurley** [comment]
Thanks very much - will give this a try.
