### ISSUE TITLE
Equivalent of Page.windowOpen event but for window.close() ?

### ISSUE THREAD

**Issue by gjsjohnmurray** [ChromeDevTools/devtools-protocol#146]
The Page.windowOpen event allows the client to hear when script running in the headless Chrome invokes window.open

Is there something equivalent that notifies the client when script invokes window.close ?

Trivial usecase is PageA containing a button that launches PageB with a window.open, specifying target="_blank". Then on PageB a button captioned "Close Me" that invokes window.close()

**Comment by JoelEinbinder** [comment]
You can make it work by listening for `Target.targetDestroyed` events from the target domain.

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
