### ISSUE TITLE
Is there a way to block websocket traffic?

### ISSUE THREAD

**Issue by mrzealot** [ChromeDevTools/devtools-protocol#147]
I'm driving Chromium from puppeteer but this seems like a more fundamental issue (as I could naturally circumvent a puppeteer API limitation by using raw DevTools protocol). My problem is that when a webpage initiates a WebSocket connection, the initial request (before the upgrade) doesn't show up as a `requestIntercepted` event for me (which I'd be able to block as usual), only as a `webSocketCreated` event, or a `webSocketWillSendHandshakeRequest` event, neither of which is cancelable afaik.

So (as the title says), is there a way to block (or even intercept or modify) websocket traffic on the protocol level? If not, could you maybe suggest a workaround? Thanks!

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
