### ISSUE TITLE
Intercept breaking with chrome v72.0.3626.81

### ISSUE THREAD

**Issue by farhan-sauce** [ChromeDevTools/devtools-protocol#148]
Hi,

I will appreciate if someone can help me out, the issue is related to chrome beta v72.0.3626.81.

So, `Network.requestIntercepted` never triggered the second time, it works fine for the first time when we set `Network.setRequestInterception`, but fails on the second time.

I use the following commands to setup interception
```
await this.sendCommandAsync('Network.setCacheDisabled', { cacheDisabled: true })
await this.sendCommandAsync('Network.clearBrowserCache')
await this.sendCommandAsync('Network.setRequestInterception', { patterns })
```

And then listen for `Network.requestIntercepted` and send `Network.continueInterceptedRequest`.

But somehow it works for the first time only and never receive `Network.requestIntercepted` event when I `setRequestInterception` second time.

**Note**: this works fine in chrome v71 (stable) and breaks in beta only.

Thanks

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
