### ISSUE TITLE
Difference between Javascript execution time as provided by the Performance tab and JS Profiler tab?

### ISSUE THREAD

**Issue by goelayu** [ChromeDevTools/devtools-protocol#149]
I see a huge difference between the javascript execution time as provided by the performance tab in chrome developer tools vs the total time taken by the javascript profiler  ( excluding the idle time ). 
My understanding of the difference is, that the javascript time provided by the performance tab only accounts for the user defined code however the javascript profiler takes into consideration the javascript code defined inside chrome or/and v8. I am however not sure and don't know if there is a way to confirm this. 

Can anyone explain to me the exact difference between the time reported by performance tab specifically for "JS Frame" when you group by activities and the time reported by the JS profiler?

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
