### ISSUE TITLE
Is it possible to have multiple search strings in Debugger.searchInContent?

### ISSUE THREAD

**Issue by AshDee** [ChromeDevTools/devtools-protocol#150]
I had tried the Debugger.searchInContent with a single string and it works. Is it possible to have multiple search string for the command?

Having the functionality would be good to narrow down the search to particular keywords.

**Comment by JoelEinbinder** [comment]
I'm not sure what you mean. Can you solve this with regex?

**Comment by AshDee** [comment]
Hi @JoelEinbinder , currently I have the following code

`const search = await client.send('Debugger.searchInContent',{scriptId:script_Id,query:'webpack'});`

Here the search comes up good, but the problem is it also returns the results where webpack is part of tags.

I would like to search for specific words like WebpackJSON, webpackpolyfill. Regex is an option but would still give that one false answer.

**Comment by AshDee** [comment]
Hi @JoelEinbinder , I believe I would need only a single word to search in the content as of now. So closing the issue. But it would be good if there would be a option in future to search multiple words other than using RegEx  :-)
