### ISSUE TITLE
[Network] Get postData of intercepted request?

### ISSUE THREAD

**Issue by vladlavrik** [ChromeDevTools/devtools-protocol#151]
Hi.

Is there a way to get a request body (postData) when intercepting the request with `Network.setRequestInterception`?

There is an excellent method for getting a response body (`getResponseBodyForInterception`), but I can’t find how I can get the request body.

I know that I can solve this problem after the release of this feature - #129.
In this case, I can use the `Network.getRequestPostData` method.

But maybe there is some way to solve my problem today?

**Comment by Gdocal** [comment]
I can see post data in Network.requestWillBeSent event

![image](https://user-images.githubusercontent.com/11136265/52524755-a9fb9880-2c98-11e9-9650-1d450f71586e.png)
Maybe you can use it

**Comment by vladlavrik** [comment]
Thanks for the answer.
But to intercept requests, I need to listen to the `Network.requestIntercepted` event for mutation of the request.
But there is no `postData` in the payload for this event.
There is also no `requestId` property so that I can't link requests received from the `Network.requestIntercepted` and the `Network.requestWillBeSent` events.

**Comment by Gdocal** [comment]
> Thanks for the answer.
> But to intercept requests, I need to listen to the `Network.requestIntercepted` event for mutation of the request.
> But there is no `postData` in the payload for this event.
> There is also no `requestId` property so that I can't link requests received from the `Network.requestIntercepted` and the `Network.requestWillBeSent` events.

You can match data from  requestIntercepted and requestWillBeSent in the same way as it is done in puppeteer

**Comment by vladlavrik** [comment]
> You can match data from requestIntercepted and requestWillBeSent in the same way as it is done in puppeteer

I was aware of this approach. Unfortunately, this is not a reliable solution - two or more requests with identical URL, method and headers can be confused.
But it seems the only possible so far.
Thank you very much for your help!
I'm closing the issue.
