### ISSUE TITLE
Page.lifecycleEvent: "networkIdle" event is not fired in some cases

### ISSUE THREAD

**Issue by IliaBrahinets** [ChromeDevTools/devtools-protocol#154]
Seems that when a page with content-type "text/xml" is requested, "networkIdle" event is not fired.
Code to reproduce:
```
const CDP = require('chrome-remote-interface');
async function example() {
    let client;
    try {
        client = await CDP({port:"9222"});
        // extract domains
        const {Page} = client;
        await Page.enable();
        await Page.setLifecycleEventsEnabled({enabled:true});
        Page.lifecycleEvent ((args, type)=> console.log(args.name));
        await Page.navigate({url: 'https://medium.com/feed/haawk'});
        //delay 10 seconds
        await (new Promise((resolve,error)=> setTimeout(resolve, 10000)));
    } catch (err) {
        console.error(err);
    } finally {
        if (client) {
            await client.close();
        }
    }
}
example();
```
Expected result: "networkIdle" event was fired
Actual result: "networkIdle" event was not fired
Generated events:
```
init
DOMContentLoaded
load
firstPaint
firstContentfulPaint
firstTextPaint
firstImagePaint
firstMeaningfulPaintCandidate
networkAlmostIdle
firstMeaningfulPaint
```

Chromium is opened with headless:false
72.0.3617.0 (Developer Build) (64-bit)
Revision - 99a174b7b1d13e53dbb2cd3aab84ba589c862d86-refs/heads/master@{#609904}

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
