### ISSUE TITLE
Building a Resource/Request Tree

### ISSUE THREAD

**Issue by pmurley** [ChromeDevTools/devtools-protocol#156]
I'd like to use the data from DevTools to construct a resource tree for an arbitrary site, starting from the root document down through all resources loaded. For example, I'd love to be able to use the data in `network.Initiator` to (semi)-reliably tie a request to the (previously loaded) resource that requested it. My understanding is that, as it stands, `network.Initiator` often doesn't give enough information to do that. I'm seeing lots of "`other`" values in `Network.Initiator.Type`, for example.

It's easy enough to do at frame-level using `Page.getResourceTree`. However, I'm having trouble building a hierarchy of resources within each frame.

I realize this is a complex task, given all of the different ways resources can be loaded. Just wondering if anyone had thoughts on a good way to do this, or anyone knew of a capability that already exists for this. Thanks!

**Comment by patrickhulce** [comment]
@pmurley you might want to look into the code over in Lighthouse that does this. You're right there's definitely a lot of information missing, but you can still go pretty far with what's there.

https://github.com/GoogleChrome/lighthouse/blob/3546168161230ac59f86887c0a771fce21661026/lighthouse-core/computed/page-dependency-graph.js#L122-L300

**Comment by pmurley** [comment]
Thanks, that's very useful! My project is in Go, so I think I'll probably end up just re-implementing a lot of that logic, but that's much better than starting from scratch!
