### ISSUE TITLE
Is there a way to get element selector / XPath via the protocol?

### ISSUE THREAD

**Issue by vsemozhetbyt** [ChromeDevTools/devtools-protocol#158]
Is there a way to get the same result as the "Copy selector" / "Copy XPath" element context menu item provides?

**Comment by JoelEinbinder** [comment]
Sure. The relevant code: https://cs.chromium.org/chromium/src/third_party/blink/renderer/devtools/front_end/elements/DOMPath.js?type=cs&sq=package:chromium&g=0&l=191

**Comment by vsemozhetbyt** [comment]
Do you mean to reimplement the tree walking and to construct the selector / XPath gradually? Is there no way to get them through a protocol API call, say, from puppeteer? If no, would it be handy to add?

**Comment by JoelEinbinder** [comment]
We don’t have a specific protocol command to do that. As you can see, we compute the value on the devtools front end. Is there some reason that wouldn’t work for your use case?

**Comment by vsemozhetbyt** [comment]
Sorry, that was a question in SO about this, and the user may want some simple solution without reimplementing. Thank you for the answer, it seems I can close the issue, as I've already advised adopting the implementation from the mentioned code.
