### ISSUE TITLE
FirstMeaningfulPaint event not getting triggered on first navigation

### ISSUE THREAD

**Issue by NivedhaSenthil** [ChromeDevTools/devtools-protocol#159]
The lifecycle event `FirstMeaningfulPaint` is not getting triggered always for the first navigation done immediately after opening browser. But gets triggered instantaneously when trying to navigate for the second time. Happens only in particular environment. 
Browser is opened with following args in clean state.
```
        '--remote-debugging-port=port',
        '--disable-features=site-per-process,TranslateUI', 
        '--enable-features=NetworkService,NetworkServiceInProcess',
        '--disable-renderer-backgrounding',
        '--disable-backgrounding-occluded-windows',
        '--disable-background-timer-throttling',
        '--disable-background-networking',
        '--disable-breakpad',
        '--disable-default-apps',
        '--disable-hang-monitor',
        '--disable-prompt-on-repost',
        '--disable-sync',
        '--force-color-profile=srgb',
        '--safebrowsing-disable-auto-update',
        '--password-store=basic',
        '--use-mock-keychain',
        '--user-data-dir=user-profile',
```

Setting proxy server args did not help for this case. 

System Details:

node -v : v11.0.0
npm -v : 6.4.1
Chromium:73.0.3665.0
Mac OS High Sierra, version : 10.13.3
Model Name:	MacBook Pro
Model Identifier:	MacBookPro14,1
Processor Name:	Intel Core i5
Processor Speed:	2.3 GHz
Number of Processors:	1
Total Number of Cores:	2
L2 Cache (per Core):	256 KB
L3 Cache:	4 MB
Memory:	16 GB

Reference downstream issue: https://github.com/getgauge/taiko/issues/393

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
