### ISSUE TITLE
Is there a way to listen to user events in the browser?

### ISSUE THREAD

**Issue by lagenar** [ChromeDevTools/devtools-protocol#16]
Hello, I'm trying to use the devtools protocol via a websockets connection to navigate to a page and listen to events generated by the user like mouse moves, clicks, inputs, etc.
I know I could inject some javascript to add event listeners or similar but my ideal solution would be to not need to inject any javascript in the page.
Is there any way to do this at the moment?

**Comment by westy92** [comment]
I had a similar question [here](https://github.com/cyrus-and/chrome-remote-interface/issues/169).

Evaluating custom JavaScript was a lot cleaner than I thought it would be.  You can find my example implementation [here](https://github.com/westy92/html-pdf-chrome/blob/22122a0f761d96caf4ad5d958d80c4ffbf1bc971/src/CompletionTrigger.ts#L83).  I have examples listening for events, callbacks, DOM elements to appear, and variables to be set.  I have timeouts in place but your code could be even cleaner without them.

**Comment by kensoh** [comment]
Nice implementation @westy92 thanks for sharing!

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
