### ISSUE TITLE
When using flat protocol, messages are routed to the target via the sessionId attribute.

### ISSUE THREAD

**Issue by leksito** [ChromeDevTools/devtools-protocol#160]
http://localhost:9222/json/list
```
[
    {
        "description": "",
        "devtoolsFrontendUrl": "/devtools/inspector.html?ws=localhost:9222/devtools/page/90C1A35F08B6317C052A3A4429491B63",
        "id": "90C1A35F08B6317C052A3A4429491B63",
        "title": "about:blank",
        "type": "page",
        "url": "about:blank",
        "webSocketDebuggerUrl": "ws://localhost:9222/devtools/page/90C1A35F08B6317C052A3A4429491B63"
    }
]

```

I'm use _Target.attachToBrowserTarget_ to get sessionId:
`{'id': 1001, 'result': {'sessionId': '81DD0C3461871103A0467DD8D0393E2C'}}`

then I use _Target.sendMessageToTarget_ to navigate using _Page.navigate_:
```
{
    "id": 1002,
    "method": "Target.sendMessageToTarget",
    "params": {
        "message": "{\"id\": 1502, \"method\": \"Page.navigate\", \"params\": {\"url\": \"http://www.google.com\"}}",
        "sessionId": "81DD0C3461871103A0467DD8D0393E2C"
    }
}
```
and get the error _"When using flat protocol, messages are routed to the target via the sessionId attribute."_.

What is mean flat sessionId mode? 
Why I got this error if _sessionId_ is defined?

**Comment by roblourens** [comment]
I think you are supposed to call `Page.navigate` directly with the sessionid

**Comment by aslushnikov** [comment]
@leksito Pease check out the https://github.com/aslushnikov/getting-started-with-cdp/ on how to use Flatten protocol.

**Comment by leksito** [comment]
but when i use as in your article, i get another error:
`{u'sessionId': u'ECC037FD6FBE59522113CABDA0A9ABC0', u'id': 2, u'error': {u'message': u"'Page.enable' wasn't found", u'code': -32601}}`
