### ISSUE TITLE
Raw screenshots

### ISSUE THREAD

**Issue by nstepien** [ChromeDevTools/devtools-protocol#161]
Would it be possible to add a `"raw"` format to `captureScreenshot`?

My use case:
I use puppeteer to save screenshots, and do visual regression testing.
To do the tests I load the saved PNGs, and take fresh sceenshots as PNGs.
Comparing the PNG bytes themselves is not adequate, as Chrome will sometimes change the compression of PNG files somehow, so I use [sharp](https://www.npmjs.com/package/sharp) to decode them into raw RGB bytes. Then I simply compare the pixels, and generate a diff.
The reason I'm requesting the ability to take raw screenshots is that my tests could run faster if I could skip one png encode+decode per test.

**Comment by JoelEinbinder** [comment]
Considering that the screenshots are necessarilly base64 encoded, json encoded, sent through IPC, then decoded, I doubt that sending a large BMP file will actually give you a large performance win, if it would be faster at all. Have you bench marked it?

**Comment by MayhemYDG** [comment]
I have not benchmarked it, but I would need to be able to take raw screenshots to compare the performance anyway.
I wonder if it needs to be base64 encoded, can't the bytes be transferred as a string? Using `String.fromCharCode(0x00 /* to 0xFF */)`.

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
