### ISSUE TITLE
Background transparency in startScreencast screencastframes

### ISSUE THREAD

**Issue by varunarora** [ChromeDevTools/devtools-protocol#162]
Hi there! Thank you for CDP.

I am working on a project where it is important that we construct a video with transparency from a rendered webpage with animations. This is an alternative to scripting an After Effects timeline to do generate custom motion graphics videos at scale. Decided not to go down the `xvbf` path because transparency is important; imagine rendering the graphics on images or videos coming from a different pipeline.

I have tentatively decided to use Puppeteer w/ CDP's `Page.startScreencast`. I am struggling to figure out how to get background transparency on the frames I get on `screencastframe` events. Note that the pages rendered have no `background-color` properties set. Regardless of whether I format and write it as `jpg` or `png`.

This isn't a problem when using the `captureScreenshot`, however. I achieved it using this (https://github.com/GoogleChrome/puppeteer/issues/344#issuecomment-323105959) very helpful suggestion:

```
page._client.send(
  'Emulation.setDefaultBackgroundColorOverride',
  { color: { r: 0, g: 0, b: 0, a: 0 } }
);
```

The difference in the output between `Page.startScreencast` and `Page.captureScreenshot` is:

![frame0](https://user-images.githubusercontent.com/629203/54394252-995c8a80-4669-11e9-82c3-2c05f6103940.jpg)

and

![screenshot](https://user-images.githubusercontent.com/629203/54394248-95306d00-4669-11e9-8f86-e2f8103a5e67.png)

(This second image background is transparent; try dragging it around)

Obviously, in the `Page.startScreencast`, I can get a solid color background using `Emulation.setDefaultBackgroundColorOverride` working just fine. But with any color with an alpha layer, it seems like the base background remains black.

My eventual goal is to merge these frames using FFMPEG. And if the above question doesn't have an easy answer, to set a green chroma key-able background, but I wish to not go down that path.

Thank you for your help!

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
