### ISSUE TITLE
`generateTestReport` method defined twice

### ISSUE THREAD

**Issue by jugglinmike** [ChromeDevTools/devtools-protocol#163]
The documentation currently lists two methods for what is ostensibly the same behavior:

- [`Page.generateTestReport`](https://chromedevtools.github.io/devtools-protocol/tot/Page#method-generateTestReport)
- [`Testing.generateTestReport`](https://chromedevtools.github.io/devtools-protocol/tot/Testing#method-generateTestReport)

I can't tell if this is intentional, but anecdotally, `Testing.generateTestReport` doesn't seem to work in Chromium 73.0.3683.75. Also, the website's search feature doesn't recognize `Page.generateTestReport`:

![2019-03-26-cdp-search-results](https://user-images.githubusercontent.com/677252/55027058-bb93c800-4fda-11e9-93b0-01ca54a4d6d8.png)

**Comment by pavelfeldman** [comment]
i'll remove `Testing.generateTestReport`, @paulirish ^^ what's up with search?

**Comment by paulirish** [comment]
>  what's up with search?

I'll fix it.

**Comment by jugglinmike** [comment]
Thanks!
