### ISSUE TITLE
Unable to download file in Headless Chrome

### ISSUE THREAD

**Issue by UsharaniA** [ChromeDevTools/devtools-protocol#164]
Hi,
Am using WebdriverIO for my automated scripts and i can see the script is running successfully in headless mode  except the file download  from the application ,i have surfed the entire internet but still my problem is not resolved.

Can you please help me and also posting my configuration below,

const wdioConfig = require('./wdio.conf.js');

wdioConfig.config.capabilities = [{
    //maxInstances: 1,
        browserName: 'chrome',
        chromedriverVersion: '2.43',
        chromeOptions: {
           
            args: ['--headless', '--disable-gpu', '--window-size=1366,768'],
            prefs: {    
               'download.default_directory': 'C:\\Users\\n276546\\Downloads',
                'download.prompt_for_download':false,
                'download.directory_upgrade':true,
                'Page.setDownloadBehavior': { 'behavior': 'allow', 'downloadPath': 'C:\\Users\\n276546\\Downloads' },
              },
     
       
        }
    }];

wdioConfig.config.services =  ['selenium-standalone','chromedriver']
wdioConfig.config.seleniumLogs ='./Seleniumlogs'

exports.config = wdioConfig.config;

**Comment by UsharaniA** [comment]
Finally i could able to download using webdriverIO.

const unirest = require('unirest');

let session = browser.session();
// key sessionId is webdriverio implementation, debug your session object
let sessionId = session['sessionId'];
let params = {
'cmd': 'Page.setDownloadBehavior',
'params': {'behavior': 'allow', 'downloadPath': 'C:\gitNodejs\art-automation-test\CucumberWebdriverIO\testResults\temp'}};

unirest
.post('http://localhost:4444/wd/hub/session/' + sessionId + '/chromium/send_command')
.send(JSON.stringify(params))
.end();

My Config file:

browserName: 'chrome',
chromedriverVersion: '2.46',
chromeOptions: {

        args: ['--headless', '--disable-gpu', '--window-size=1366,768','--disable-web-security','--no-sandbox','--incognito'],
        prefs: {    
            'download.default_directory': 'C:\\gitNodejs\\art-automation-test\\CucumberWebdriverIO\\testResults\\temp',
            'download.prompt_for_download':false,
            'download.directory_upgrade':true,
            "safebrowsing.enabled":false,
            "safebrowsing.disable_download_protection":true
          },

   
    }

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
