### ISSUE TITLE
Debugger domain runs before Network Domain.

### ISSUE THREAD

**Issue by AshDee** [ChromeDevTools/devtools-protocol#166]
I have two different javascript files

network.js- has an async function with Network.requestWillBeSent
2.debugger.js- has an async function with Debugger.scriptParsed
The logic is to run the network domain and get the scripts. Debugger code will update the hashes based on the scripts acquired by the network domain. Since debugger runs before the network domain, I do not get the intended result

I exported them as modules and loaded it in an index.js file.

Is there a way to have debugger code run after network code is finished?

I have tired async/await and also promises in index.js, but didn't work out.

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
