### ISSUE TITLE
Network.responseReceived response.status is always 200, including non-existent 404 pages

### ISSUE THREAD

**Issue by mrj** [ChromeDevTools/devtools-protocol#171]
The `status` field of [`response`](https://chromedevtools.github.io/devtools-protocol/tot/Network#type-Response) objects returned by [`Network.responseReceived`](https://chromedevtools.github.io/devtools-protocol/tot/Network#event-responseReceived) events after a [`Page.navigate`](https://chromedevtools.github.io/devtools-protocol/tot/Page#method-navigate) command is always 200, even when I navigate to a non-existent page that returns status 404.

How can I tell if a navigation succeeded?

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!

**Comment by mrj** [comment]
OK, thanks.

However the "Improve article" link on https://web.dev/nfc/ took me to the https://github.com/GoogleChrome/web.dev/blob/master/src/site/content/en/blog/nfc/index.md page of this repository.

**Comment by TimvdLippe** [comment]
Your link points to the web.dev repository. This is the devtools-protocol repository.

**Comment by mrj** [comment]
Sorry Tim, I thought this comment activity concerned a web.dev issue that I created today. I see now it's about another issue created ten months ago.
