### ISSUE TITLE
Subresource integrity status

### ISSUE THREAD

**Issue by daresais** [ChromeDevTools/devtools-protocol#172]
Is there any way to check the status of an subresource integrity check? The only thing I noticed is the error log to console that the check failed. By now I have to check the link and script tags for the integrity attribute and just believe that it passed the SRI check when there is no error log. Is there maybe a event emitted that indicates that a check happend including the result? If not would that be a good addition to the protocol?

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
