### ISSUE TITLE
Enabling touch emulation on webview also affects the outer page host 

### ISSUE THREAD

**Issue by AglaiaWang** [ChromeDevTools/devtools-protocol#173]
https://github.com/electron/electron/issues/18438
when set touch emulation in webview use Emulation.setEmitTouchEventsForMouse,  this window affected.
electron developer has helped me to check the procedure what send to devtools-protocol  no problem, so, please check this question why it's happen?

env: 
chrome: 73.0.3683.121
electron: 5.0.1

**Comment by jkzing** [comment]
Is there any updates on this?

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
