### ISSUE TITLE
CPU throttling settings during emulation do not persist between navigates

### ISSUE THREAD

**Issue by arthesh** [ChromeDevTools/devtools-protocol#174]
We're seeing that the CPU throttling settings during emulation do not persist between navigates when debugging with dev tools - possibly due to a new process being spawned due to [Site Isolation](https://www.chromium.org/Home/chromium-security/site-isolation) . 

Repro steps : 
1. Launch Chrome , navigate to url (eg - https://en.m.wikipedia.org/wiki/Echo_parakeet ) 
2. Launch devtools , enter device emulation mode and set throttling settings to 'Low end mobile' 
3. Also launch Chrome task manager to observe the CPU stats for the tab process - It should be close 100% as CPU is being throttled per 'Low end mobile' settings.
4. Navigate to another url ( say www.office.com) and watch the stats in Chrome Task manager - The CPU no longer is pegged close to 100% and the Process Id changes - indicating the CPU throttling settings are not in force.

Have you'll run into this ? It also seems to affect Webpagetest.org agents running on Windows that use the devtools command (Emulation.setCPUThrottlingRate) before the initial navigate. 

Also I'm wondering if there a workaround or a way to chain dev tools commands for navigate/setting CPU emulation rate that ensure that the new process is throttled before actual navigate ?

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
