### ISSUE TITLE
Consider implementing incoming websocket message fragmentation

### ISSUE THREAD

**Issue by mvdan** [ChromeDevTools/devtools-protocol#175]
This is a direct continuation of https://github.com/ChromeDevTools/devtools-protocol/issues/24.

I understand why this was never a priority; incoming messages aren't meant to be very large. Outgoing messages can easily get large, on the other hand; screenshots are an easy example.

To support moderately sized incoming messages, the buffer size for them was increased to 100MiB, as mentioned in that issue. That's certainly an improvement, but not ideal. It leaves developers with two options:

* Use a small buffer, meaning that users may see silent crashes if they do anything moderately sized
* Use a large buffer, meaning increased memory usage for every single user

Either way, Chrome dies with no useful error sent - not to the websocket connection, and not to stderr.

If fragmentation is implemented (I assume it wouldn't be that much code), then clients can get the best of both worlds - support large messages without needing to always allocate large buffers.

I'm in a particularly difficult spot, as I develop a library in Go that's similar to Puppeteer; see https://github.com/chromedp/chromedp/issues/395. Making the buffer small and big are both bad choices, because I'm forcing that on all the users. Making the buffer size configurable just moves the decision to the user, and in my opinion that's an internal detail that they shouldn't care about.

If the plan is still to not implement this, I'd at least ask that Chrome give a useful error message. Otherwise, debugging the silent crashes is an unnecessary adventure :)

**Comment by JoelEinbinder** [comment]
@aslushnikov this sounds reasonable to me

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!

**Comment by mvdan** [comment]
Thanks. A bit of a bummer that this wasn't pointed out earlier, as it seems like I've wasted a year on this :) I've raised https://bugs.chromium.org/p/chromium/issues/detail?id=1069431.

**Comment by TimvdLippe** [comment]
Sorry for that. It is stated in the README. (Although I am updating that to be more clear to prevent confusion in the future).
