### ISSUE TITLE
The package.json license field should be `BSD-3-Clause`

### ISSUE THREAD

**Issue by krisselden** [ChromeDevTools/devtools-protocol#177]
The LICENSE file included in this repository and at https://chromium.googlesource.com/chromium/src/+/master/LICENSE is the text of the [3-Clause BSD License](https://opensource.org/licenses/BSD-3-Clause).

The value of the license field of the package.json is supposed to be a SPDX short identifier and should be `BSD-3-Clause`.

The current value makes it so that when we update devtools-protocol version in our internal npm registry we need to get legal to review the custom license because it is not a valid SPDX short identifier.

**Comment by TimvdLippe** [comment]
@krisselden Could you confirm that https://github.com/ChromeDevTools/devtools-protocol/pull/210 would solve your issue?
