### ISSUE TITLE
Target.createTarget background param does not work

### ISSUE THREAD

**Issue by evanrolfe** [ChromeDevTools/devtools-protocol#178]
When sending the [Target.createTarget](https://chromedevtools.github.io/devtools-protocol/tot/Target#method-createTarget) command with the param `background: true` set, it does not open the target in the background, instead it opens the tab and focuses on it which is the default behaviour.

**Steps to reproduce**
* Chrome Version 75.0.3770.100 (Official Build) (64-bit)
* Ubuntu 18.04
* Node v10.15.3

Running this code with and already open google chrome (non-headless):
```js
const puppeteer = require('puppeteer-core');

(async () => {
  const browser = await puppeteer.connect({browserURL: 'http://localhost:9222'});
  const page = await browser.newPage();
  const client = await page.target().createCDPSession();
  await client.send('Target.createTarget', {url:'https://google.com', background: true});
})();
```

**Current Behaviour**
The `browser.newPage();` line opens a new tab to the url `about:blank` (which is expected), then `client.send('Target.createTarget'...` opens a new tab at https://google.com and switches the focus to that new tab:
![Selection_011](https://user-images.githubusercontent.com/9274/60575538-a239af00-9d73-11e9-858e-b12d03ad03df.png)

**Expected Behaviour**
It should keep the focus on the tab at url `about:blank`.

Thanks.

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!

**Comment by VikramTiwari** [comment]
I created a ticket for a similar bug on crbug. I think it was incorrectly marked as wontfix. https://bugs.chromium.org/p/chromium/issues/detail?id=1247421
