### ISSUE TITLE
childNodeInserted and other DOM events not firing

### ISSUE THREAD

**Issue by mattfysh** [ChromeDevTools/devtools-protocol#179]
Hi there, I'm having trouble getting the `childNodeInserted` DOM event to fire, in fact I've subscribed to all DOM events and the only one I see gets fired (twice) is the `DOM.documentUpdated` event.

In the page I'm loading, i can see that the event does trigger in the browser:

```js
document.addEventListener("DOMNodeInserted", function(e) {
  console.log('DOMNodeInserted')
});
```

To get around this, I'll look into `MutationObserver`, but I'm not sure if that API will be suitable in the long term

Any ideas why the DOM domain events are not firing, and/or how to debug?

**Comment by JoelEinbinder** [comment]
For efficiency, those events are only sent for nodes that have been previously requested.

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
