### ISSUE TITLE
TypeScript definition of protocol

### ISSUE THREAD

**Issue by paulirish** [ChromeDevTools/devtools-protocol#18]
I've seen a number of developers interested in this.

**Currently, there is no officially maintained typescript definition file.** We have no immediate plans to begin offering one, but I wanted to point at a great alternative from the community.

I recommend looking at these two projects:
➡️    @krisselden's [chrome-debugging-client](https://github.com/krisselden/chrome-debugging-client) (see [tot.ts](https://github.com/krisselden/chrome-debugging-client/blob/master/protocol/tot.ts)) 
➡️    @nojvek's [chrome-remote-debug-protocol](https://github.com/nojvek/chrome-remote-debug-protocol) (see [crdp.d.ts](https://github.com/nojvek/chrome-remote-debug-protocol/blob/master/lib/crdp.d.ts)). ([a fork by @roblourens](https://github.com/roblourens/chrome-remote-debug-protocol) is currently more maintained)

_Comment edited March 2018_

**Comment by JustinRyanH** [comment]
I'm working on project to solve this. I'm open to forking off the section relating to Type definitions to it's own repo and collaborating. https://github.com/MajorHard/Enz/tree/proto_type

**Comment by krisselden** [comment]
https://github.com/krisselden/chrome-debugging-client already works well for automating Chrome, can run headless chrome just fine, just call spawn with additional `--headless` arg.

@JustinRyanH what are you solving? Why are you starting over?

@paulirish what's missing? just an example of running a test?

**Comment by paulirish** [comment]
@krisselden nothings really missing for me! was just sending folks your way for now.

**Comment by krisselden** [comment]
@paulirish I updated the tests on travis to use headless instead of the x virtual frame buffer https://travis-ci.org/krisselden/chrome-debugging-client and added it to the README example.

**Comment by JustinRyanH** [comment]
@krisselden I think I've confused `chrome-debugg-protocol` with your repo. Use the current work as a learning experience.

**Comment by auchenberg** [comment]
Ping @nojvek @roblourens

**Comment by nojvek** [comment]
I built a project a while ago that pulls in the protocol.json files from v8 and chrome repos and automatically generate crdp.d.ts files. https://github.com/nojvek/chrome-remote-debug-protocol/blob/master/lib/crdp.d.ts

The generator lives here: https://github.com/nojvek/chrome-remote-debug-protocol/blob/master/src/protocolToCrdp.ts

@roblourens has a fork that pulls in specific versions of protocol.json and builds version specific crdp.d.ts for use in vscode chrome debugger and node inspector. https://github.com/roblourens/chrome-remote-debug-protocol/blob/master/src/main.ts

crdp.d.ts is promise based and works great with async await: https://github.com/nojvek/chrome-remote-debug-protocol/blob/master/lib/crdp.d.ts

Do note that chrome debugging protocol changes quite a bit, maintaining by hand will quickly get out of hand.

**Comment by Bnaya** [comment]
It will be very useful to have `@types` package with the protocol declarations so all of the projects as `chrome-remote-interface` will depend on to create their own declarations.

What would be the name of such package?

**Comment by bazyli-brzoska** [comment]
@Bnaya `@types` packages have to map to actual NPM packages.

**Comment by nojvek** [comment]
@bnaya you can `npm install chrome-remote-debug-protocol` which is a pure
typings package.

https://www.npmjs.com/package/chrome-remote-debug-protocol

Since the typings are auto-generated from official google's protocol.json
files, they are relatively up-to-date. If you are targeting a specific
version of chrome, it's easy to generate typings from that specific version
of protocol.json for v8 and blink.

**Comment by paulirish** [comment]
This has been contributed to the repo in https://github.com/ChromeDevTools/devtools-protocol/pull/90

It's shipped in the npm package devtools-protocol@0.0.547074


Thanks @nojvek !
