### ISSUE TITLE
Debugging in Service Worker

### ISSUE THREAD

**Issue by cpx0rpc** [ChromeDevTools/devtools-protocol#183]
I tried to use the Debugger inside a Service Worker target, but it does not seem to work. There is an error saying "(Debugger.enable): Script execution is prohibited." Did I do anything wrong or the Debugger is not currently supported in Service Worker yet? Below is my code.

```
const puppeteer = require('puppeteer');
(async () => {
	const browser = await puppeteer.launch({
		headless: false,
		defaultViewport: null,
		devtools: true
	});
	const page = await browser.newPage();
	await page.goto('https://pptr.dev/');
	const client = await page.target().createCDPSession();
	
	const swTarget = await browser.waitForTarget(target => target.type() === 'service_worker');

	const session = await swTarget.createCDPSession();

	session.send('Debugger.enable');

	session.on('Debugger.scriptParsed', ({scriptId, url, stLine, stCol, endLine, endCol, execContextId, hash, execContextAuxData, isLiveEdit, srcMapURL, hasSrcURL, isModule, len, stackTrace}) => {
		console.log("scriptURL: ", url);
	});

	session.on('Debugger.scriptFailedToParsed', ({scriptId, url, stLine, stCol, endLine, endCol, execContextId, hash, execContextAuxData, isLiveEdit, srcMapURL, hasSrcURL, isModule, len, stackTrace}) => {
		console.log("scriptURL: ", url);
	});
})();
```

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
