### ISSUE TITLE
How to change download behavior?

### ISSUE THREAD

**Issue by mohamed0123** [ChromeDevTools/devtools-protocol#184]
I am working on JavaScript website to extract all anchor's absolute URL using puppeteer, but in some cases there is anchor's have download function to download documents and i just want absolute URL without download it

    <a href="javascript:;" onclick="downLink(0, '/somepath/download.ashx?id=102');">Download</a>

    <a class="text" href="javascript:openDatasheetDownload('/procatalaog/Datasheet.jsp;jsessionid=3901737BA7133?productId=(%5bsaui,j430000%5d)', 'PDF DATASHEET', 'width=300,height=500,resizable=yes,menubar=yes')">Download</a>
and if we try catch the absolute URL like normal we will just catch for example something like this 'downLink(0, '/somepath/download.ashx?id=102' as the URL

so if your team can add an option to change download behavior to be just change page url to download link in browser

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
