### ISSUE TITLE
`highlightNode` for multiple nodes?

### ISSUE THREAD

**Issue by qqilihq** [ChromeDevTools/devtools-protocol#185]
Is there any chance to highlight multiple nodes at once?

When calling [`highlightNode`](https://chromedevtools.github.io/devtools-protocol/tot/Overlay#method-highlightNode), the previous selection disappears. I'd like it to stay to highlight e.g. multiple nodes which match a given query.

Any way to achieve this?

**Comment by psybuzz** [comment]
Overlay.highlightNode does have an optional "selector" parameter.  If passed with a CSS selector, it should highlight all matching nodes, so if you build a unique CSS selector per node, you can chain it into a long combination string with commas and use that.

This approach doesn't scale so well, though :/

**Comment by qqilihq** [comment]
I had indeed overlooked that, probably it was just recently added? -- thank you!

However, as you say, due to scaling, I'd really prefer to have one of the following options:

1. Either having something such as `highlightAdditionalNode`
2. Having the possibility to pass more than a single `id` to the function

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
