### ISSUE TITLE
Setting host request header via Fetch

### ISSUE THREAD

**Issue by imranazad** [ChromeDevTools/devtools-protocol#188]
It turns out it's no longer possible to set host request header via Fetch.continueRequest:

```
browser.on('Fetch.requestPaused', (params) => { 
            var headers = [
                    {'name': 'Host', value: '1' }
                ]

            browser.cdp('Fetch', 'continueRequest', {
                requestId: params.requestId,
                headers: headers
            })
         })
```

It turns out because chromium has now marked this as an unsafe header:

https://github.com/chromium/chromium/blob/d280a10b60101c5eacd4e130110aec74a633ab79/services/network/public/cpp/header_util.cc#L22

Any ideas of how I can get around this?

Thanks

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
