### ISSUE TITLE
Roadmap for experimental features

### ISSUE THREAD

**Issue by EdwinVanVliet** [ChromeDevTools/devtools-protocol#191]
Hi,

I'm interested in using the Fetch domain, which is still marked as experimental. The current implementation offers me the functionality I need, but I don't feel comfortable using it because of potential breaking changes.

Is there any timeline or roadmap map indicating when this domain is going to be stable?
https://chromedevtools.github.io/devtools-protocol/tot/Fetch 

With kind regards,
Edwin

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
