### ISSUE TITLE
Dump/Restore tab (whole state: cookies, DOM content, etc.) 

### ISSUE THREAD

**Issue by bitliner** [ChromeDevTools/devtools-protocol#193]
I would like to dump the full state of a tab (DOM content, cookies, requests done, etc.), so that I can restore that in another Chrome process.

Would it be possible?

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
