### ISSUE TITLE
dispatchMouseEvent - movementX/movementY is not changed

### ISSUE THREAD

**Issue by lolrpa** [ChromeDevTools/devtools-protocol#194]
Hi,
When calling dispatchMouseEvent movementX/movementY is not changed. 
Some websites track the movementX/movementY to trigger menu, so it is impossible to use devtools protocol to trigger such menu.

Is there a chance that movementX/movementY will be implemented?

Also pptr mouse.move is dependent on this feature. https://github.com/GoogleChrome/puppeteer/issues/4973

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
