### ISSUE TITLE
Will DOMSnapshot.captureSnapshot have includeEventListeners?

### ISSUE THREAD

**Issue by kicktheken** [ChromeDevTools/devtools-protocol#195]
My understanding is that `DOMSnapshot.getSnapshot` will be deprecated in favor of `DOMSnapshot.captureSnapshot`. However, `captureSnapshot` is missing the `includeEventListeners` option that `getSnapshot` has (see https://chromedevtools.github.io/devtools-protocol/tot/DOMSnapshot#method-getSnapshot). Moving forward, will `captureSnapshot` have an option to include eventListeners? If not, how do we get the event listeners?

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
