### ISSUE TITLE
.send(method: string) still not tight enough

### ISSUE THREAD

**Issue by ali-habibzadeh** [ChromeDevTools/devtools-protocol#196]
The commands passed into .send method are still loose hanging strings. While this library is a very good step forward, it would be great to have enums or specific methods so we don't have to pass string names of commands in as they are prone to typos and not easily manageable.

**Comment by connorjclark** [comment]
If you use typescript this isn't an issue. Works with `.js` files too.

**Comment by ali-habibzadeh** [comment]
God help us if you got the job of contributing to Dom. Will end up with DOMSession.send(“document.querySelectorall”).passArgs([“.selector”]);

**Comment by connorjclark** [comment]
cool
