### ISSUE TITLE
DevTools Target.createBrowserContext returns error not browserContextId

### ISSUE THREAD

**Issue by crislin2046** [ChromeDevTools/devtools-protocol#197]
Not sure the spot for this, as I'm not sure the cause, so I'll report here:

Chrome version: 77.0.3865.120  Channel: stable
OS Version: 10.0
Flash Version: 

## Steps to reproduce the problem:
1. Start chrome --headless process and connect to devtools protocol websocket
2. issue command with method: "Target.createBrowserContext", and params: {} (or no params with same result)
3. Notice response: { code: -32000, message: 'Not allowed' } 

## What is the expected behavior?
Not sure. This could be intended behavior. 

## What went wrong?
The following is all probably too complicated as I'm just trying to create a separate incognito-like profile which I take it from the docs that a browser context is. Any help on how to do that (or get Target.createBrowserContext) will be much appreciated. 

Anyway, checking the source I see that if access_mode_ is not equal to AccessMode::kBrowser then this error will be produced. As per: 

https://cs.chromium.org/chromium/src/content/browser/devtools/protocol/target_handler.cc?type=cs&g=0&l=802

I checked the DevTools docs and the source for how to connect to DevTools protocol so that access_mode_ is kBrowser but I cannot discover how. 

I see there's a way to hit kAutoAttachOnly and kRegular modes (by switching on flags set by Target.setAutoAttach and Target.setDiscoverTargets and I could not find a way in the DevTools docs or source, or command-line flags at peter.sh to get access_mode_ to be kBrowser.

I tested setting --enable-automation flag and it still errored. 

I tested using various params as well: {}, undefined, and {sessionId} and it was all not allowed. 

Something else strange and moderately unrelated is that I *can* use Runtime.addBinding, but it looks like that is related to Target.exposeDevToolsProtocol (which is only accessible if kBrowser is the access mode), so I'm probably incorrect thinking they're related. 

## Did this work before? 

Yes There was a (possibly unrelated) fix here: https://codereview.chromium.org/2630533002/

Seems to be reported again since chrome 71. See recent comments at: https://bugs.chromium.org/p/chromium/issues/detail?id=679350

Other people seem to be reporting it here: https://github.com/thecodingmachine/gotenberg/issues/15

Also reported at [cr bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1015260).

**Comment by crislin2046** [comment]
Sorry this was an issue with mode not being flattened. This works fine in flattened session mode, if attachToTarget({flatten:true,...}) is used.

**Comment by Rajkumar0718** [comment]
i can't able to get browserContext id by Target.createBrowserContext method. it alway throws a {"id":1740602218,"error":{"code":-32000,"message":"Not allowed"}} .How can i solve it?
