### ISSUE TITLE
Knock knock

### ISSUE THREAD

**Issue by auchenberg** [ChromeDevTools/devtools-protocol#2]
Yo, What are you guys up to? 😎 Going for a open protocol called "DevTools protocol"?

**Comment by pavelfeldman** [comment]
@auchenberg it took you like 30 seconds to discover this one, I wonder how that works.

To answer your question: baby steps towards that direction. We want to open it for the discussion, primarily as a forum to discuss what it can and can not do; provide guidance; accept feature requests. Just to see whether it works.

What we are also doing separately is making a big part of our API public, considering naming it LTS and committing to the ongoing support for it. We are looking at the APIs that are used for automation: WebDriver, Lighthouse and alike. A lot of external questions on the protocol we get are automation-related.

**Comment by auchenberg** [comment]
My job is to follow every step you guys make, or simply to follow you on GitHub 😄 

Sounds good, and makes sense.
