### ISSUE TITLE
Accessing chrome dev tools on a chrome node of selenium grid

### ISSUE THREAD

**Issue by bimalviswam** [ChromeDevTools/devtools-protocol#202]
I use selenium docker images (hub and chrome node) to build a selenium grid. My goal is to intercept a request which is invoked form chrome node when I run my test. Is this possible with chrome dev tools protocol? any directions?

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
