### ISSUE TITLE
Page.startScreencast does not hide scrollbars when chrome is started with --hide-scrollbars

### ISSUE THREAD

**Issue by drbenway6667** [ChromeDevTools/devtools-protocol#203]
Hi,

Current Usage:
when starting chrome / chromium with the `--hide-scrollbars` argument
and using the devtools `Page.startScreencast` and then listening for `Page.screencastFrame` the current screencasts image response (the `data` string Base64-encoded compressed image) does not hide scrollbars as expected.

Expected Usage:
That when chrome / chromium is launched with the `--hide-scrollbars` argument it would also hide the scrollbars in the `screencastFrame `responses created by the devtools  `Page.startScreencast` process

Example: [https://ibb.co/0CMty4X](https://ibb.co/0CMty4X)

Ref Chromium Issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1024647

Cheers,
Henry

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
