### ISSUE TITLE
DOM.attributeModified

### ISSUE THREAD

**Issue by sapshah** [ChromeDevTools/devtools-protocol#208]
While using puppeteer, I have the following snippet

```
await client.send('DOM.enable');
client.on('DOM.childNodeRemoved', () => {
			console.log('hello dom node removed');
		});
```

I goto the inspect element and try to remove a node. However that will not throw any event. I am unable to get any event around attribute modified, inserted nodes or removed nodes from DOM domain.

I am trying to do so using inspect element. Is there something else that I need to do?

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
