### ISSUE TITLE
Call "copy full XPath" from the protocol?

### ISSUE THREAD

**Issue by youshy** [ChromeDevTools/devtools-protocol#217]
Is there a way to call `copy full XPath` from the protocol?

**Comment by patrickhulce** [comment]
That's not implemented at the protocol level, but at the frontend (see https://cs.chromium.org/chromium/src/third_party/devtools-frontend/src/front_end/elements/DOMPath.js?type=cs&sq=package:chromium&g=0&l=211-232).
