### ISSUE TITLE
Is there a cross-language test-suite for DevTools protocol clients?

### ISSUE THREAD

**Issue by d4h0** [ChromeDevTools/devtools-protocol#218]
Hello,

I'm working on a DevTools protocol client for Rust, and I'm wondering if there is some kind of test-suite that can be used to test clients.

For example, a JSON file with requests and expected responses would be useful.

With that, I could convert the supplied requests into code that uses my library and then check if the response matches.

I use the JSON files from this repo to automatically generate the types needed for the client (and writing tests by hand is therefore not really an option).

If there isn't a cross-language test-suite, is there some other test-suite?

If there is, for example, a test-suite for a JavaScript client, then maybe the following approach would be possible:

1. create a WebSocket proxy that will be placed between the test-suite and the DevTools protocol server
2. save received requests and responses
3. read stdout of the test-suite and try to find out which tests failed/succeed

**Comment by paulirish** [comment]
I personally don't know of any tests aside from these: https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/web_tests/http/tests/inspector-protocol/

**Comment by d4h0** [comment]
@paulirish: Thank you. I will try to extract usable information from these tests.
