### ISSUE TITLE
Are failing requests silent? Feature request: method to get request ErrorReason

### ISSUE THREAD

**Issue by cris691** [ChromeDevTools/devtools-protocol#219]
Hello, this is not an implementation issue, but I'm sorry if it's still not in scope. If so, please close because I certainly don't mean to clog up your issue page with something irrelevant. 

Anyway, I'm basing the following question and feature request from looking at and using

https://chromedevtools.github.io/devtools-protocol/tot/

If a request fails, due to any of the [Network.ErrorReason](https://chromedevtools.github.io/devtools-protocol/tot/Network/#type-ErrorReason)s, is there any way to get/be notified that 

1) request failed and
2) the ErrorReason for failure?

From investigating, the only way I see is to use [Fetch.requestPaused](https://chromedevtools.github.io/devtools-protocol/tot/Fetch/#event-requestPaused) event (or its [deprecated equivalent](https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-continueInterceptedRequest). However, it seems this is unreliable as `responseErrorReason` will only be set if request was intercepted in response stage.

The reason I'm looking for this is because I'm building a [remote browserview](https://github.com/dosyago/BrowserGap) and want to provide people with information when a request fails. Just like the Chrome error pages, e.g.

![chrome-error-page-example](https://user-images.githubusercontent.com/22254235/86900841-70a1b380-c13e-11ea-86f2-daa08839ee04.JPG)

I'm probably incorrect that there's no way to get this information reliably, so sorry for this issue, because I'm sure people would have run into issues with, say, puppeteer hanging silently on some URLs. I tried looking for that and finding workarounds based on that, but could not find anyone asking something similar. Anway, I'm really sorry if this is not clear, if this is a valid issue please ask any questions you need to clarify. 

Thanks, and awesome work on the Chrome Remote Debugging Protocol! 😄

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!

**Comment by cris691** [comment]
Thanks @TimvdLippe ! 😄
