### ISSUE TITLE
How to get a real DOM Node as in browser？

### ISSUE THREAD

**Issue by rawbin-** [ChromeDevTools/devtools-protocol#22]
DOM.resolveNode will return a node;
Runtime.evaluate will also return a node;
```
Runtime.evaluate({
    expression:`
            var targetDOM = document.querySelector('#target');
            targetDOM.click();
            targetDOM;
        `
}).then(({result}) => {
       // result.click is not a function
});
```

But neither of them is same as the `targetDOM` above;

How can I get the targetDOM  out of the runtime?

**Comment by pavelfeldman** [comment]
You can't get a real DOM node over the wire, you can only get a handle to node, which Runtime.evaluate returns. You would need to call 
```
Runtime.callFunctionOn({ objectId: result.objectId, functionDeclaration: `function () { this.click(); }`)
```

in order to invoke `click()` on that handle in the page.

**Comment by rawbin-** [comment]
@pavelfeldman  it make sense ,thanks a lot~
