### ISSUE TITLE
DevTools Lacks Differentiation Between Code Currently Unused At Present Moment Vs. Entirely Unused/Dead Code

### ISSUE THREAD

**Issue by crwirth** [ChromeDevTools/devtools-protocol#223]
As stated, from my understanding of the Chrome DevTools Protocol, there is no differentiation between code that is unused for a specific page load and code that is not utilized throughout an entire application. Instead, any code not utilized at the time of the page load is labeled entirely unused which is a little misleading, and unhelpful for cleanup of an application. In the future, it would be nice to see support for a feature along this line to aid with refactoring and cleanup.

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
