### ISSUE TITLE
Modifying response headers

### ISSUE THREAD

**Issue by matti** [ChromeDevTools/devtools-protocol#227]
I have:
```
Fetch.enable {
  patterns: [
    {
    requestStage: 'Request'
  },{
    requestStage: 'Response'
  }
  ]
}
```

And now I'm seeing responses in `Fetch.requestPaused` - but I can not override/modify the headers in the response messages - only for requests.

How to modify response headers?

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!

**Comment by matti** [comment]
I tried, but I don't see how to file an issue under that component, see https://bugs.chromium.org/p/chromium/issues/detail?id=1139932
