### ISSUE TITLE
Protocol error (Runtime.runScript): No script with given id

### ISSUE THREAD

**Issue by cchen124** [ChromeDevTools/devtools-protocol#228]
I am trying to execute the below script using the Chrome DevTools Protocol in Puppeteer tests. I receive a protocol error of "Protocol error (Runtime.runScript): No script with given id" at `await client.send('Runtime.runScript', {scriptId: idScriptString});`. 

       `await client.send('Runtime.enable');
       const idScript = await client.send('Runtime.compileScript', {expression: "sessionStorage[\"ShellOverrides\"] = JSON.stringify({UniversalMeControlEnabled:true})", sourceURL: "", persistScript: true});
        const idScriptString = JSON.parse(JSON.stringify(idScript)).scriptId;
        await client.send('Runtime.runScript', {scriptId: idScriptString});
        await client.send('Page.enable');
        await client.send('Page.reload');`

Does anyone have a suggestion of how to begin to debug this?

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
