### ISSUE TITLE
changelog to big to be seen on github

### ISSUE THREAD

**Issue by UXDart** [ChromeDevTools/devtools-protocol#230]
Hello. the file https://github.com/ChromeDevTools/devtools-protocol/blob/master/changelog.md
is bigger than 1mb so it doesn't show, you need to see it in raw mode. is it possible to hide the very old changes so we can see the file with format, and not in raw mode?

Thanks!

**Comment by paulirish** [comment]
fixed by #273

but #230 changed it again.
