### ISSUE TITLE
Achieve the usage of Page.getResourceContent API

### ISSUE THREAD

**Issue by anuragiiits** [ChromeDevTools/devtools-protocol#231]
Is there an alternative API or method to achieve the result of the API - [Page.getResourceContent](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-getResourceContent) ?
The API is in experimentation mode for quite a long time and I wanted to use achieve this usage in production. If there isn't a way to achieve it, could it be taken as a feature request?

Thanks.

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
