### ISSUE TITLE
Frame navigated event did not trigger

### ISSUE THREAD

**Issue by kanishkadistill** [ChromeDevTools/devtools-protocol#232]
Details for the environment.
Platform / OS version: Ubuntu 18.04.5 LTS
URLs (if applicable):https://www.nokia.com/about-us/investors/investor-relations-events/
Node.js version: v10.22.0

What steps will reproduce the problem?
Framenavigated event does not trigger for few frames on this page.
Frame1 Upcoming events
Frame2 Past events

Code:

```let client = await CDP();
const { Network, Page } = client;
await Network.enable();
await Page.enable();
await Page.navigate({ url: 'https://www.nokia.com/about-us/investors/investor-relations-events/' });
Page.frameAttached((frame) => {
        console.log("frameAttached", frame)
});
Page.frameNavigated((frame) => {
        console.log("frameNavigated", frame)
}); 
```

Expected result:
Frame navigated events for all the frames on the page.

Actual result:
Frame navigated event was triggered only for the mainframe.

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
