### ISSUE TITLE
Method for Proxy Authentication

### ISSUE THREAD

**Issue by SwitchGM** [ChromeDevTools/devtools-protocol#234]
Hey there, I'm currently using devtools with a proxy and have been very unlucky in finding a way to authenticate with it. I'm very sure that there is a method, as the docs have [Network.AuthChallange](https://chromedevtools.github.io/devtools-protocol/tot/Network/#type-AuthChallenge) , and [Network.AuthChallangeResponse](https://chromedevtools.github.io/devtools-protocol/tot/Network/#type-AuthChallengeResponse) types. Unfortunatly I have been unable to find any example code using these or any code using devtools to authenticate proxies.

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!

**Comment by ethaniel** [comment]
Here is an example how I did it in PHP:
```php
// enable request interception (important!!!)
$page->getSession()->sendMessageSync(new Message('Network.setRequestInterception', ['patterns' => [['urlPattern' => '*']]]));
$page->getSession()->on('method:Network.requestIntercepted', function (array $params): void {
		if (isset($params["authChallenge"])) {
			echo "Authorizing Proxy" . PHP_EOL;
			$page->getSession()->sendMessageSync(
				new Message('Network.continueInterceptedRequest', ['interceptionId' => $params["interceptionId"], 'authChallengeResponse' => ['response' => 'ProvideCredentials', 'username' => "proxy_username", 'password' => "proxy_password"]])
			);

		} else {

			$GLOBALS["kdmid_page"]->getSession()->sendMessageSync(
				new Message('Network.continueInterceptedRequest', ['interceptionId' => $params["interceptionId"]])
			);

		}

	}
});
```
