### ISSUE TITLE
Reference to an experimental type in a non-experimental method

### ISSUE THREAD

**Issue by zaygraveyard** [ChromeDevTools/devtools-protocol#236]
`Target.createTarget()` takes an optional `browserContextId` parameter of type `Browser.BrowserContextID`
But `Browser.BrowserContextID` is marked as **experimental** while neither `Target`, `Target.createTarget()` or the `browserContextId` parameter are marked as **experimental**

So either the parameter should be marked as **experimental** or the type shouldn't be

https://github.com/ChromeDevTools/devtools-protocol/blob/dee574b5f9d6663dffa0fa6d109c57a0a3010f94/pdl/browser_protocol.pdl#L8154

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!

**Comment by zaygraveyard** [comment]
For reference, here it is: https://bugs.chromium.org/p/chromium/issues/detail?id=1254337
