### ISSUE TITLE
Could Chrome Devtools debug the Worker Coverage in the Chrome browser？

### ISSUE THREAD

**Issue by daffy6537** [ChromeDevTools/devtools-protocol#237]
I can only get the main thread javascript Converages data， Workers failed。

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
