### ISSUE TITLE
What ScriptDuration metric from Performance.getMetrics means?

### ISSUE THREAD

**Issue by TanyaOstrovskaya** [ChromeDevTools/devtools-protocol#239]
I'm using [Performance.getMetrics](https://chromedevtools.github.io/devtools-protocol/tot/Performance/) method from Java  via `okhttp3.WebSocket` interface to measure performance of app opened by Selenium Webdriver.

I receive values of metrics: LayoutDuration, SriptDuration, etc.

1. Could you please provide docs about what those numbers means? What exactly does **SriptDuration** measure - what steps of JS code execution? Existing docs do not say anything about it. And I saw bunch of unanswered questions like [this one](https://stackoverflow.com/questions/48630430/i-need-more-info-about-puppeteer-page-metrics-and-queryobjects) - such doc is truly required.

2. Why would I receive different values of metrics launching same script on the same machine? What factors does the SriptDuration value depend on?

3. How do metrics match with Performance profile recorded from Chrome dev tools tab? E.g. I assume EvaluateScript event duration is equal to SriptDuration value. Am I right?
![image](https://user-images.githubusercontent.com/18058690/112515044-fafe7600-8da6-11eb-8c66-08016e0080e5.png)

Thank you for the answer!

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
