### ISSUE TITLE
Page.setDownloadBehaviour deprecated

### ISSUE THREAD

**Issue by roshansourav** [ChromeDevTools/devtools-protocol#242]
Since this `https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-setDownloadBehavior` is deprecated. So, what is alternative solution.?
I am trying to download a file using puppeteer in nodejs.

**Comment by pbi-qfs** [comment]
`https://chromedevtools.github.io/devtools-protocol/tot/Browser/#method-setDownloadBehavior`

**Comment by roshansourav** [comment]
Hey @pbi-qfs  . Thanks man. Its is working super fine without any error.
BUT, i am facing 1 more problem here. That file is being downloaded but it is not being saved in the current folder.
I am using parameter { behavior: 'allow', downloadPath: './' } .
Is there anything which needs to be changed?

**Comment by pbi-qfs** [comment]
I would guess that the value of "current folder" might be different from the client's and from Chrome's perspective. To be on the save side, specify the path absolutely, e.g. `'/tmp/'`.

**Comment by roshansourav** [comment]
Yes, this worked for me. Thank you so much @pbi-qfs . Thanks Man.

**Comment by tsaindane-cloudwiz** [comment]
@roshansourav Its not working for me. The file does not get downloaded in /tmp path in my case. could u plz help me?
