### ISSUE TITLE
Question: difference between any and object without properties?

### ISSUE THREAD

**Issue by joffrey-bion** [ChromeDevTools/devtools-protocol#245]
In the protocol definitions, I have seen occurrences of both `type: "any"` and `type: "object"` without any `properties` list.

What's the difference? Is it that `any` can be anything including primitives (effectively any JSON _value_) but `object` is limited to only structures with properties (effectively only JSON _objects_)?

In that case, does an `object` without properties list represent a type whose properties are unknown/dynamic?

In the typescript definitions, I noticed that most params of type `object` without properties are represented with the `Headers` interface, which is basically `{[key: string]: string}`. This would confirm my guess here. However, some are still translated into TS's `any` (e.g. `PausedEvent.data`), which is why I'm asking here.

**Comment by TimvdLippe** [comment]
As I read the `.json` file, the `"type": "object"` denote interfaces. For example, https://github.com/ChromeDevTools/devtools-protocol/blob/bc63f36a5736f930a81ec6fa7089ae710242f615/json/browser_protocol.json#L603 maps to https://github.com/ChromeDevTools/devtools-protocol/blob/bc63f36a5736f930a81ec6fa7089ae710242f615/types/protocol.d.ts#L2844

The `"type": "any"` is used to denote values of an interface itself. I don't think there is any occurrence of `"type": "object"` of a value of an interface, is there?

**Comment by joffrey-bion** [comment]
I think I might have been unclear here. The general case of `"type": "object"` indeed represents interfaces, like the one you linked to here. For this purpose, `"type": "object"` goes along with `"properties": [ ... ]`, which describes the properties of the interface.

In this question, I am specifically talking about places where `"type": "object"` is used _without_ any `"properties": [...]` along with it. For instance: https://github.com/ChromeDevTools/devtools-protocol/blob/bc63f36a5736f930a81ec6fa7089ae710242f615/json/js_protocol.json#L1090

That's an occurrence of a type `object` as a parameter of an event. It's not a reference to an existing interface declared as top-level domain type. But it's ok because it has no properties. So I guess what this means here is that it's a JSON object but without details about what properties are available.

**Comment by TimvdLippe** [comment]
Ah I see, I had missed the usage in `js_protocol.pdl`. I have asked internally for clarification on this.

**Comment by joffrey-bion** [comment]
No problem, I was also confused when I searched `browser_protocol` and didn't find my examples anymore :D
Thanks a lot for asking around!

**Comment by caseq** [comment]
@joffrey-bion, you're reading it right -- "type": "any" implies any type at all, including primitive types such as boolean/numer/string, while "type": "object" implies a JSON object (i.e. a dictionary with string keys and values of "any" type).
