### ISSUE TITLE
How to know if Network.responseReceived have a relationship to Network.dataReceived

### ISSUE THREAD

**Issue by ev1stensberg** [ChromeDevTools/devtools-protocol#25]
Is there any way to map back a size of the network request to what you'd get back from `Network.dataReceived` to `Network.responseReceived`?

**Comment by ev1stensberg** [comment]
I'm interested in getting `dataLength`, of the script that has been loaded, but that's not available under `Network.responseReceived`

**Comment by pavelfeldman** [comment]
`Network.responseReceived` is triggered when the header of the response becomes available. The body has not yet started downloading. At that point in time, we only know `Content-Length` via parsing the response header.

Then we get a series of `Network.dataReceived` events that carry information about actual network chunks. They all share `requestId` that is first mentioned in the `Network.requestWillBeSent`. It all ends up with the `Network.loadingFinished` when resource has been loaded (or `Network.loadingFailed` if it failed).

**Comment by ev1stensberg** [comment]
So both `dataRecieved` and `responseReceived` can share the same `responseId`? I couldn't find any similarities there.

**Comment by paulirish** [comment]
they share a `requestId`

**Comment by ev1stensberg** [comment]
My fault, closing this. Thanks for helping out 🥇
