### ISSUE TITLE
Can I get the browser current page?

### ISSUE THREAD

**Issue by wuchuguang** [ChromeDevTools/devtools-protocol#250]
Hello , I want to get current page , to show frontend.

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
