### ISSUE TITLE
Target.createTarget does not work with browserContextId

### ISSUE THREAD

**Issue by gilles-yvetot** [ChromeDevTools/devtools-protocol#255]
UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36

Steps to reproduce the problem:
1.Start a browser with 2 different browserContext
2. Try to create a target with a browserContextId

What is the expected behavior?
Being able to create targets on both contexts

What went wrong?
It throws an error telling me it can't find the browserContext with the `browserContextId` provided

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!

**Comment by gilles-yvetot** [comment]
@TimvdLippe thanks for letting me know. Unfortunately they don't reply overthere
