### ISSUE TITLE
Usage of DOM.highlightNode to select a node

### ISSUE THREAD

**Issue by xtof1** [ChromeDevTools/devtools-protocol#258]
I try to use this _DOM.highlightNode_ function but only get a temporary effect : the selected node change style and immediately reset to original default style.
If there a way to select the node ? Maybe it is relative to _HighlightConfig.SelectorList_ field but I don't know what are the expected values here.
My expectation is to select a node like the user would do with his mouse pointer.
Thank you in advance

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
