### ISSUE TITLE
Getting the redirect response

### ISSUE THREAD

**Issue by fracasula** [ChromeDevTools/devtools-protocol#26]
Hi,

I'm using Node.js with the [chrome-remote-interface](https://github.com/cyrus-and/chrome-remote-interface) to communicate with an headless instance of Chrome *(v59.0.3071.86)*.

I'm using the [Network.responseReceived](https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-responseReceived) method to listen to responses but on a 301 the first response I get is the one right after with a 200 like shown below:

```js
{
    url: 'http://localhost/',
    status: 200,
    statusText: 'OK',
    headers: {
        Date: 'Mon, 19 Jun 2017 09:34:06 GMT',
        Connection: 'keep-alive',
        'Transfer-Encoding': 'chunked',
        'Content-Type': 'text/html'
    }
}
```

What I was expecting was something more like this:

```js
{
    url: 'http://localhost/no_longer_available.html',
    status: 301,
    statusText: 'Moved Permanently',
    headers: {
        // ...
    }
},
{
    url: 'http://localhost/',
    status: 200,
    statusText: 'OK',
    headers: {
        Date: 'Mon, 19 Jun 2017 09:34:06 GMT',
        Connection: 'keep-alive',
        'Transfer-Encoding': 'chunked',
        'Content-Type': 'text/html'
    }
}
```

I've been going through the [docs here](https://chromedevtools.github.io/devtools-protocol/tot/Network/) but I could not find anything of help.

Is there a way to achieve this? Maybe like I would do with a non-headless Chrome by recording the network log?

Thanks.

**Comment by dgozman** [comment]
Hi,

Network.requestWillBeSent
<https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-requestWillBeSent>
contains
redirectResponse, if this request was sent as a result of redirect from the
other one.

- Dmitry

**Comment by fracasula** [comment]
It worked thanks!

```js
network.requestWillBeSent(request => {
    if (request && !!request.redirectResponse) {
        console.log('Redirect data', request.redirectResponse);
    }
});
```
