### ISSUE TITLE
CDP 1.1

### ISSUE THREAD

**Issue by geoffmmorgan** [ChromeDevTools/devtools-protocol#262]
I'm working on a project that involves connecting to very old remote devices: Chrome 38+ via the CDP. Some of these devices are using Protocol Version 1.1. The protocol seems to have been in an experimental stage at that point and generally is undocumented, but I was hoping someone might be able to point me to any remaining documentation about that protocol version and the commands available. That version also doesn't seem to expose a `/json/protocol` endpoint either, making it a bit more difficult. The 1.2 protocol mostly matches, but any other references would be appreciated.

**Comment by paulirish** [comment]
> That version also doesn't seem to expose a `/json/protocol` endpoint either

True. That (very useful) endpoint was added somewhere much later (probably in the 60s?)


--------------

1.1 was minted as a manually curated "safe subset" of the protocol that we thought wouldn't change.

I think the only "documentation" we have of it now is https://github.com/ChromeDevTools/debugger-protocol-viewer/blob/gh-pages-1.1/_data/protocol1-1.json

Chrome 38 is ~Oct 2014. Here's the full protocol as of March 2015: https://github.com/ChromeDevTools/debugger-protocol-viewer/blob/9828487a814de8757ea34db1b83b0be227fb49ca/assets/protocol.js (The oldest copy I have without diving into some old chromium/blink history)

Of course there's no guarantee of backwards compatibility, but I can't imagine there's a huge gap between this protocol and what you Chrome 38 devices speak.

**Comment by geoffmmorgan** [comment]
This is awesome, thank you so much for the quick response, this is exactly what I was looking for! Appreciate the help
