### ISSUE TITLE
devtools-bot not updating js_protocol.pdl?

### ISSUE THREAD

**Issue by szuend** [ChromeDevTools/devtools-protocol#263]
It seems that the js_protocol.pdl hasn't been updated in a while. I don't know where the source for the devtools-bot is, otherwise I would have taken a look.

**Comment by paulirish** [comment]
Thanks for the heads up. 

Fixed now: https://github.com/ChromeDevTools/devtools-protocol/commit/a5e142a6142be87f7869fbb7c5ba13022e50c2e1
