### ISSUE TITLE
Page.loadEventFired timestamp unit

### ISSUE THREAD

**Issue by hinzundcode** [ChromeDevTools/devtools-protocol#27]
How can I interpret the timestamps of `Page.loadEventFired` and `Page.domContentEventFired`? For example `40159.349892`. It can't be milliseconds since the initial request and it can't be a unix epoch with microseconds either. The documentation lacks this information.

**Comment by kdzwinel** [comment]
AFAIK it's a relative "high-resolution real time", in node you can get it by calling `process.hrtime()`. The way I'm using it: https://github.com/kdzwinel/betwixt/blob/master/src/lib/init-time.js

**Comment by paulirish** [comment]
Yes, AFAIK it's a [monotonic clock](https://www.softwariness.com/articles/monotonic-clocks-windows-and-posix/) timestamp that's generally reset when the machine is rebooted.

I think it'd be fair to add "Monotonic clock timestamp" as a description for these timestamps.

**Comment by paulirish** [comment]
Larger discussion opened on timestamps at https://groups.google.com/d/topic/chrome-debugging-protocol/X-Ts2-KygYA/discussion

**Comment by paulirish** [comment]
This was addressed in https://github.com/ChromeDevTools/devtools-protocol/commit/3cca818d9855a0d6d281cd4c13e4d2748505adb1

I believe now all timestamps are clearly described. The ones you called out are now described as:

> MonotonicTime: Monotonically increasing time in seconds since an arbitrary point in the past.

**Comment by slhck** [comment]
Just curious – is there any reason for these timestamps being arbitrary? Couldn't they be simply Unix epochs with microseconds as in `Date.now()`?
