### ISSUE TITLE
Screenshot performance

### ISSUE THREAD

**Issue by karleberts** [ChromeDevTools/devtools-protocol#28]
(I'm not sure if this issue is filed correctly with this project, but it seems plausible.)

I'd like to use Chrome in headless mode to capture screenshots as part of a test suite that is scripted w/ node (using [this](https://github.com/cyrus-and/chrome-remote-interface) module to interface with a target instance running on the local machine), but I'm noticing that taking a screenshot takes anywhere from 7-25 seconds (from when Page.captureScreenshot is sent from the client to when the response is received). 

I want to take quite a few screenshots in each run, so it ends up taking several minutes to run the test, which is just too much.

Has anyone else experienced this? I'm not sure if the issue is in the rendering of the screenshot or somewhere in the transmission of the data to the debugging client, but I'd expect to be able to fetch screenshots from a local instance very fast.

I'm using MacOS and Chrome 59, btw.

**Comment by dgozman** [comment]
@aslushnikov

**Comment by paulirish** [comment]
@karleberts can you provide a small gist or snippet of your script to do this? we use chrome-remote-interface here so that's all fine. :)

**Comment by kensoh** [comment]
@karleberts I'm using PHP websocket to talk to Chrome directly, and uses Page.captureScreenshot.

Have not experienced anything like your situation before. The capturing is fast and returns a base64 string fast, which I then convert to binary and save.

I'm also using macOS (10.12.5) and Chrome 59.0.3071.115. My screen size is 1440 x 900 (2014 macbook air). Running Chrome in visible or headless mode the Page.captureScreenshot returns data quite fast.

**Comment by paulirish** [comment]
Here's the implementation issue filed in Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=741689

We have a repro now, so watch that bug for details.

**Comment by karleberts** [comment]
@paulirish Thanks for the link, I'll watch that issue!
