### ISSUE TITLE
Inverse visualisation of diff in changelog.md

### ISSUE THREAD

**Issue by pbi-qfs** [ChromeDevTools/devtools-protocol#283]
The new `changelog.md` style is quite nice for quick review of the changes, but unfortunately the diff appears to be mirrored, i.e. added lines appear with a "-" in front while removed lines are marked with "+". This is quite confusing, especially as the lines are nicely (and wrongly) colored in red and green by the HTML renderer.

In addition, the link to the compare site should not contain the backticks in the link, so instead of

```markdown
[`4f1ab67...958f979`](https://github.com/ChromeDevTools/devtools-protocol/compare/`4f1ab67...958f979`)
```

it should read:

```markdown
[`4f1ab67...958f979`](https://github.com/ChromeDevTools/devtools-protocol/compare/4f1ab67...958f979)
```

**Comment by paulirish** [comment]
big thanks for flagging this! a shame i missed it until now.  

thank you much. :D
