### ISSUE TITLE
Page.setDocumentContent - full html or body content only

### ISSUE THREAD

**Issue by codepunkt** [ChromeDevTools/devtools-protocol#29]
I'm confused. Does Page.setDocumentContent set the full page html or does it only set the body content?

**Comment by paulirish** [comment]
@codepunkt it appears to set the full document's HTML, this would include the doctype and `html` tag. It applies via a diff-patch-style similar to virtual DOM so any nodes that shouldn't change won't.

**Comment by codepunkt** [comment]
Thanks, Paul!
