### ISSUE TITLE
It's not clear what kind of protocol is

### ISSUE THREAD

**Issue by vemv** [ChromeDevTools/devtools-protocol#299]
Hi,

while I have a basic understanding of CDP, and have successfully used it, CDP's documentation does not do a great job at describing what do they mean exactly by 'protocol'.

* Is CDP a specific, distinct protocol, like SMTP, FTP, POP, etc?
* Is CDP 'just HTTP'? A subset thereof?
* Is CDP 'just websockets'? subset thereof?
* Something else?

The way I see it, a set of type definitions like [browser_protocol.json](https://github.com/ChromeDevTools/devtools-protocol/blob/44ad3c8f38b36d826d4c1d120235798209ffa836/json/browser_protocol.json) do not constitute a protocol.

Those type definitions may be part of it, but what I believe to be missing is how communication happens.

Thanks much,

-V

**Comment by projektorius96** [comment]
It is really common thing for Google to have issues with documentation . Examples:
- Apps Scripts documentation is quite dodgy
- Google Sheets API documentation for Node.js is a unmaintained nightmare, although with help of @sofisl I've managed to figure out it .

I guess community using Google provided APIs for different tooling in generally could lay out numbers of issues related to APIs' documentation in generally .

**Comment by paulirish** [comment]
@vemv CDP sits on top of [JSON-RPC](https://en.m.wikipedia.org/wiki/JSON-RPC), though spec-wise it appears to align closest with the [1.1 Object Spec](https://jsonrpc.org/historical/json-rpc-object-specification.html).

The transport for CDP is almost entirely over websockets, though using a [pipe](https://pptr.dev/api/puppeteer.launchoptions#:~:text=false-,pipe,-optional) is supported.
