### ISSUE TITLE
Page.addScriptToEvaluateOnLoad should be renamed

### ISSUE THREAD

**Issue by paulirish** [ChromeDevTools/devtools-protocol#31]
[`Page.addScriptToEvaluateOnLoad`](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-addScriptToEvaluateOnLoad) doesn't run "on load" but runs when a new document is created. In Lighthouse we've renamed this to `addScriptToEvaluateOnNewDocument` (roughly). 

IMO it'd make sense to rename this method to avoid further confusion.

**Comment by pavelfeldman** [comment]
Pending review https://chromium-review.googlesource.com/c/559979/

**Comment by paulirish** [comment]
thx!
