### ISSUE TITLE
Disable sourceURL

### ISSUE THREAD

**Issue by hinzundcode** [ChromeDevTools/devtools-protocol#34]
Is it possible to disable source maps using the devtools protocol? In my application I use chrome headless to collect all console messages of a website (using `Runtime.consoleAPICalled`) and want to parse the stackTrace of each message, but I need full urls instead of what was stated as sourceURL.

**Comment by paulirish** [comment]
@ak239, all you

**Comment by ak239** [comment]
What you would like to see in case of anonymous script like following?
`eval('console.log(123);//# sourceURL=foo.js')`

**Comment by hinzundcode** [comment]
For anonymous functions/eval that could be an empty string.

I struggle with scripts that have a normal url, but state something different as sourceURL. Using `Debugger.scriptParsed` I can at least figure out if a sourceURL was used, but I can't access the original url.

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
