### ISSUE TITLE
Script hash

### ISSUE THREAD

**Issue by hinzundcode** [ChromeDevTools/devtools-protocol#35]
The `Debugger.scriptParsed` event contains hash of each script. What kind of hash is this? How can I calculate it myself?

**Comment by kdzwinel** [comment]
Looks like it's this one: https://cs.chromium.org/chromium/src/v8/src/inspector/v8-debugger-script.cc?l=29&rcl=a29b8877e34188cbc358c6317d949c066ef5d015
