### ISSUE TITLE
Requests with a script initiator but without an stackTrace

### ISSUE THREAD

**Issue by hinzundcode** [ChromeDevTools/devtools-protocol#37]
I often get requests (using `Network.requestWillBeSent`) with an initiator of type script but with an empty callFrames array. Is there any other way to figure out the script which caused the request?

**Comment by paulirish** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=570298 is the parent issue that should capture these cases.

![image](https://user-images.githubusercontent.com/39191/28283571-f45c7288-6ae2-11e7-8811-c76f4152ddca.png)

If you can identify a different case where you have no stack trace, then we'd want to file it as a new bug on crbug.com

**Comment by paulirish** [comment]
And FWIW here's devtools frontend implementation of extracting initator from this data: https://github.com/ChromeDevTools/devtools-frontend/blob/6bee02dbfbee47d56b1e5d9b7a7c52d7a2b75b08/front_end/network_log/NetworkLog.js#L167-L213

It appears to not do much else in the case you described.

**Comment by dgozman** [comment]
Note that many times synchronous stack is empty because request was triggered by native code, but async stack trace usually has good JS reference.

**Comment by hinzundcode** [comment]
Thanks for your replies. I'll have a look at the bug reports.

For the moment I try to use the frame hierarchy and to match scripts to their corresponding requests (and their initiators) to fill the missing pieces. I hope that leaves me with a complete graph of all script dependencies.
