### ISSUE TITLE
Network.Response.headersText always empty/not existing

### ISSUE THREAD

**Issue by maurice2k** [ChromeDevTools/devtools-protocol#38]
I'm looking for a way to get the raw response headers using headless chrome.

The current stable 1.2 version of the devtools protocol documents a field called `headersText` within the `Response` object but it's never included in the response, which is technically ok as the field is marked "optional".

Is there a flag somewhere to "activate" the optional fields?

Or is there a way to get a list of all headers like in HAR format (headers is an array of objects with name/value properties)?

**Comment by pavelfeldman** [comment]
https://chromium-review.googlesource.com/c/565139 should have fixed it.

**Comment by maurice2k** [comment]
Hi @pavelfeldman,

thanks for pointing me to the pull request!
It seems to fix the problem for HTTP/1.x but not for HTTP/2 as there are no "text" headers...

I was looking for a way to get the raw header information that was sent from the server (spelling, order) like it is in the HAR format. Any ideas how to solve this for HTTP/2?

(`headers` should have been an array of objects...)

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
