### ISSUE TITLE
Target values for `Network.emulateNetworkConditions()`

### ISSUE THREAD

**Issue by akleiner2** [ChromeDevTools/devtools-protocol#39]
Hi there! I had a quick question re: the spec for `Network.emulateNetworkConditions`. What would be the upper/lower bounds on input params like `downloadThroughput` and `uploadThroughput`? Just trying to get a ballpark idea of what these params represent. 

Thanks again!

**Comment by akleiner2** [comment]
Going to assume that `latency` is in ms, and `downloadThroughput` and `uploadThroughput` are in kb/s, since that's what the units in the dev tools are. Closing this out!

**Comment by karanjthakkar** [comment]
@akleiner2 Maybe this helps: https://github.com/ChromeDevTools/devtools-protocol/issues/47#issuecomment-326502266 👍

**Comment by paulirish** [comment]
added details now: https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-emulateNetworkConditions
