### ISSUE TITLE
Security.SecurityState and Security.CertificateId are missing from 1.2

### ISSUE THREAD

**Issue by kdzwinel** [ChromeDevTools/devtools-protocol#4]
As reported [here](https://github.com/ChromeDevTools/debugger-protocol-viewer/issues/73) by @gcooney.

v1.2 references but doesn't define `Secuirty.SecurityState` and `Security.CertificateId`.

**Comment by JustinRyanH** [comment]
I've started building these protocol into a Typescript Definitions, and I noticed this issue too. I think I have a solution for my current situation involving these, but I'm more curious about understanding the intention of referencing an unstable domain in a stable protocol file.

**Comment by ui4j** [comment]
@JustinRyanH is your project open source?

**Comment by JustinRyanH** [comment]
Yes.  https://github.com/MajorHard/Enz/tree/proto_type 

My suggestion for a patch would be to make Security references to stable marked as experimental. 
However, if that isn't possible I will just use the Typescript AST to find unresolved references and turn them to build generic empty interfaces.

**Comment by paulirish** [comment]
This will be fixed by https://chromium-review.googlesource.com/c/chromium/src/+/744729
