### ISSUE TITLE
References to exceptionRevoked which doesn't exist

### ISSUE THREAD

**Issue by also** [ChromeDevTools/devtools-protocol#40]
In the [description of the `Runtime.exceptionRevoked` event](https://github.com/ChromeDevTools/devtools-protocol/blob/02471710b8da985aab130096ead7a5c524329934/json/js_protocol.json#L380)
> The id of revoked exception, as reported in <code>exceptionUnhandled</code>.

`exceptionUnhandled` isn't described anywhere. Is it supposed to refer to `exceptionThrown`?

**Comment by paulirish** [comment]
yes it is.

i've drafted a patch to fix the typo: https://chromium-review.googlesource.com/c/v8/v8/+/653237

**Comment by paulirish** [comment]
fixed a while ago.

thx for reporting ryan
