### ISSUE TITLE
printPDF to return a stream

### ISSUE THREAD

**Issue by jifeon** [ChromeDevTools/devtools-protocol#41]
Currently `printToPDF` returns a `base64` encoded string. It works great in general, but we are generating a bit huge PDFs - min 40MBs, they include lot of pages with high resolution images. Keeping such big data in memory causes performance and memories issues with node. It would be nice to take PDF content as a stream, or as a file. 

Currently we are thinking about workaround with page per page printing. But it dramatically increases complexity of the service. So my question is: are there any plans to support streams for `printToPDF`?

ref https://github.com/cyrus-and/chrome-remote-interface/issues/216

**Comment by caseq** [comment]
We already have a provision for returning bulky data in the protocol -- the IO domain lets you read streams backed either by raw temp files or by blobs. This is currently only used for returning trace data from the Tracing domain, but we're considering using it in other places as well. I think what you're suggesting makes perfect sense, but please file this on crbug.com so it's easier to track as part of the DevTools backlog.

**Comment by jifeon** [comment]
thx @caseq. The issue is [here](https://bugs.chromium.org/p/chromium/issues/detail?id=748956)

**Comment by jifeon** [comment]
Related issue https://bugs.chromium.org/p/chromium/issues/detail?id=748956 was closed. Can it help with pushing this feature forward?

**Comment by cyrus-and** [comment]
FYI it seems to be available *now*, see for example: https://github.com/cyrus-and/chrome-remote-interface/issues/216#issuecomment-1046001497
