### ISSUE TITLE
Switch To Frame

### ISSUE THREAD

**Issue by JarrodCTaylor** [ChromeDevTools/devtools-protocol#42]
I am needing to interact with the contents of an iframe, and so far coming up short in my attempts. Does the devtools-protocol have anything analogous to https://w3c.github.io/webdriver/webdriver-spec.html#switch-to-frame or is there an alternative way to accomplish that interaction?

**Comment by kensoh** [comment]
I'm not aware of that, for me I set the frame context by defining this way - 
`frame_context = document.evaluate('(//frame|//iframe)[@name="'+frameInfo+'" or @id="'+frameInfo+'"]',document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotItem(0).contentDocument;`

Then perform subsequent interactions with CSS selector - 
`frame_context.querySelector()...`

Or with XPath selector -
`document.evaluate(selector,frame_context,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotItem(0)...`

The Chromy project based on chrome-remote-interface also has an implementation for iframe - https://github.com/OnetapInc/chromy/blob/e0cfc3038349d0bf2bc0e452806ac7f2b5ba7cc0/src/document.js#L34

**Comment by paulirish** [comment]
@JarrodCTaylor take a look at https://github.com/GoogleChrome/puppeteer/blob/master/lib/FrameManager.js

Basically you can listen to `Page.frameAttached`, `Runtime.executionContextCreated` etc events.. 
Then  you can do a `Runtime.evaluate` using the new `contextId` param.
