### ISSUE TITLE
Target.createBrowserContext doesn't have a clean browser state

### ISSUE THREAD

**Issue by joelgriffith** [ChromeDevTools/devtools-protocol#43]
https://chromedevtools.github.io/devtools-protocol/tot/Target/#method-createBrowserContext

When connecting to an existing Chrome instance, and launching multiple `createBrowserContext`'s there can be data leakages in things like local-storage (and potentially other things: cookies, indexdb...)

Repo steps:

1. Launch Chrome
2. Connect and create a new target with `createBrowserContext`
3. Connect to that browser context, open a page, set some keys into local storage
4. Repeat Step 2 and then lookup that local-storage key. It shouldn't return a value but does.

According to the docs:
>  Similar to an incognito profile but you can have more than one

This leads me (and I assume others) to believe that each context will have a clean browser slate (no prior persisted data). I could be misunderstanding the motivation behind this API, and this is expected, but the docs lead me to believe that this is a bug.

Curious to hear thoughts on this or if there's a better way to generate a Target that is clean? Thanks!

**Comment by dgozman** [comment]
I believe this only works in headless Chrome. Do you get "Not supported" error in response to createBrowserContext?

**Comment by joelgriffith** [comment]
I should have clarified: I'm running with these flags `--headless --disable-gpu`. I do see that response when not using headless to answer your question!

**Comment by joelgriffith** [comment]
Going to close this as it's likely been fixed (over a year old).

**Comment by Rajkumar0718** [comment]
i can't able to get browserContext id by Target.createBrowserContext method. it alway throws a {"id":1740602218,"error":{"code":-32000,"message":"Not allowed"}} .How can i solve it?

**Comment by akmal-abar** [comment]
> i can't able to get browserContext id by Target.createBrowserContext method. it alway throws a {"id":1740602218,"error":{"code":-32000,"message":"Not allowed"}} .How can i solve it?

fucking read 😭
