### ISSUE TITLE
Sending 'Enter' key event on input field

### ISSUE THREAD

**Issue by selfrefactor** [ChromeDevTools/devtools-protocol#45]
The issue was originally submitted to 'chrome-remote-interface' repo at [https://github.com/cyrus-and/chrome-remote-interface/issues/226](https://github.com/cyrus-and/chrome-remote-interface/issues/226) and I was redirected to this repo.

---

| Component | Version
|-|-
| Operating system	  	 	| Ubuntu 16.10
| Node.js					| 8.1.2
| Chrome/Chromium/...		| 60.0.3112.78 (Official Build) beta (64-bit)
| chrome-remote-interface	| 0.24.3

Is Chrome running in a container? NO

---
My issue is with firing 'Enter' key on input field.

I thought that the code `await Input.dispatchKeyEvent({ type: 'rawKeyDown', keyIdentifier: 'Enter' })` would work, but it did not.

This is my code:

```js
const CDP = require("chrome-remote-interface")
const chromeLauncher = require("chrome-launcher")
const getPort = require("get-port")
const R = require("rambdax")

const chromeFlags = [
  "--disable-gpu",
  "--disable-sync",
  "--no-first-run",
  "--headless",
  "--window-size=1366,768"
]

const main = async () => {
  try{
    const port = await getPort()
    const chrome = await chromeLauncher.launch({
      chromeFlags,
      port,
    })
    const client = await CDP({ port })
    const { Page, Runtime, Input } = client

    await Promise.all([
      Page.enable(),
      Runtime.enable(),
    ])

    await Page.navigate({ url : 'https://www.google.com' })
    await Page.loadEventFired()
    await R.delay(1000)
    await Input.dispatchKeyEvent({ type: 'char', text: 'm' })
    await R.delay(200)
    await Input.dispatchKeyEvent({ type: 'char', text: 'o' })
    await R.delay(200)
    await Input.dispatchKeyEvent({ type: 'char', text: 'e' })
    await R.delay(200)
    await Input.dispatchKeyEvent({ type: 'rawKeyDown', keyIdentifier: 'Enter' })
    await R.delay(3000)
  }catch(err){
    console.log(err)
  }
}

main()
```

Any help will be appreciated. Thanks!

**Comment by kdzwinel** [comment]
I don't remember the details, but I do remember having the exact same issue. This code worked for me: https://github.com/ChromeDevTools/EmulatedDeviceLab/blob/master/lib/device.js#L192 Try providing `windowsVirtualKeyCode: 13` instead of `keyIdentifier: 'Enter'`.

**Comment by kdzwinel** [comment]
Also, looking at the protocol [docs](https://chromedevtools.github.io/devtools-protocol/tot/Input/#method-dispatchKeyEvent), you are providing invalid value for `keyIdentifier`. For enter key you should provide sth like 'U+000D'.

**Comment by selfrefactor** [comment]
Thank you so much for the help. 

It is a bit late now to test it out, but it looks very promising.

**Comment by kensoh** [comment]
I'm communicating directly to Chrome via websocket (without going through chrome-remote-interface). For me I use Input.dispatchKeyEvent and '\r' to send the enter key event and it works for my use case (simulating enter on input boxes).

**Comment by selfrefactor** [comment]
Guys, both suggested solutions by @kdzwinel and @kensoh are working, thank you so much.

Feel free to close the issue.

**Comment by BenHayak** [comment]
What about Tab keys? or Arrow keys?  How do you scope the TAB to move to the next "focusable" element in the page (like a real keyboard tab key would) and not simply add indent to the input box?

**Comment by activeliang** [comment]
```js
async pressedEnter() {
  await Input.dispatchKeyEvent({ "type": "rawKeyDown", "windowsVirtualKeyCode": 13, "unmodifiedText": "\r", "text": "\r" })
  await Input.dispatchKeyEvent({ "type": "char", "windowsVirtualKeyCode": 13, "unmodifiedText": "\r", "text": "\r" })
  await Input.dispatchKeyEvent({ "type": "keyUp", "windowsVirtualKeyCode": 13, "unmodifiedText": "\r", "text": "\r" })
}
```
it works for me

**Comment by ethaniel** [comment]
You should be fine with just:
```
async pressedEnter() {
  await Input.dispatchKeyEvent({ "type": "rawKeyDown", "windowsVirtualKeyCode": 13 })
  await Input.dispatchKeyEvent({ "type": "char", "windowsVirtualKeyCode": 13 })
  await Input.dispatchKeyEvent({ "type": "keyUp", "windowsVirtualKeyCode": 13 })
}
```

**Comment by mertunsall** [comment]
Used this here!
https://github.com/browser-use/browser-use/pull/3675

Thanks a lot!
