### ISSUE TITLE
Document unit for Network.emulateNetworkConditions

### ISSUE THREAD

**Issue by TimvdLippe** [ChromeDevTools/devtools-protocol#47]
The documentation does not list the units of `emulateNetworkConditions`. #39 was a similar issue where the user assumed kb, but my tests do not seem to confirm this unit.

**Comment by karanjthakkar** [comment]
@TimvdLippe based on a preliminary lookup through the code, it seems like it is actually in bytes. Ref: https://cs.chromium.org/chromium/src/third_party/WebKit/Source/devtools/front_end/audits2_worker/lighthouse/lighthouse-background.js?q=downloadThroughput&sq=package:chromium&dr=CSs&l=12040

**Comment by paulirish** [comment]
See also https://github.com/ChromeDevTools/devtools-frontend/blob/e590d46db490ab3dce0cec24993a31c88ae0142e/front_end/sdk/NetworkManager.js#L211-L225

Yes the unit is bytes.

**Comment by paulirish** [comment]
I have a patch incoming to address this and #39 
https://chromium-review.googlesource.com/c/651030/

**Comment by paulirish** [comment]
patch is landed 
https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-emulateNetworkConditions

**Comment by TimvdLippe** [comment]
Thanks Paul for the clarifications!
