### ISSUE TITLE
Window size is weird when printToPDF

### ISSUE THREAD

**Issue by quangbuule** [ChromeDevTools/devtools-protocol#48]
Hi,

I attempted to print 10inch x 10inch PDF, I declared some media queries in the html file, and the result is not as expected:

(blue texts are ones that match the queries)
![](https://user-images.githubusercontent.com/5992964/29298187-2f638574-8190-11e7-9dd8-19227f9c1e34.png)

Here is my gist:
https://gist.github.com/quangbuule/4b781d581f203e59358111c075252d32

**Comment by quangbuule** [comment]
From the example, the window size that is detected by media queries is about 7.5~7.6 x 5.6~5.7 inch while the expected size is 10x10 inch.

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
