### ISSUE TITLE
Want to understand working of Animation API

### ISSUE THREAD

**Issue by ApoorvSaxena** [ChromeDevTools/devtools-protocol#49]
Want to understand the working of Animation API, and the type of animations that it is able to record.
https://chromedevtools.github.io/devtools-protocol/tot/Animation/

Following questions will give better clarity:
- Does it record animations implemented via CSS only or JS as well?
- What about animations in GIF or video?
- It gives information about the animation such as duration, how will this API behave in case of animation using JS (when moving an image pixel by pixel)

**Comment by paulirish** [comment]
@ApoorvSaxena Good questions...

It's only getting CSS animation data right now.   

No JS. Anims in JS arent' really detectable at the platform level. (even requestAnimationFrame is used by non-animations)

No gifs, no video.

**Comment by ApoorvSaxena** [comment]
@paulirish was able to deduce the same, thanks for clarifying

**Comment by piyushsri** [comment]
@paulirish any plans to include these in future?

**Comment by paulirish** [comment]
@piyushsri nope. :)

**Comment by facelite** [comment]
okay
