### ISSUE TITLE
Console/Log are missing from 1.2

### ISSUE THREAD

**Issue by kdzwinel** [ChromeDevTools/devtools-protocol#5]
from @linclark, moved from [here](https://github.com/ChromeDevTools/debugger-protocol-viewer/issues/69)

> It looks like Console was removed because it is deprecated, but the Log entry (which replaces some of the functionality) is still experimental, so that's not included either.

**Comment by pthieu** [comment]
Bumped into this last night. The `Log.entry` event does not handle `console.log`'s in the browser.

**Comment by samir-mahendra** [comment]
There is a `Runtime.consoleAPICalled` that will let you receive `console.log` calls from the browser.  You'll get the event after calling `Runtime.enable`.

**Comment by lesteenman** [comment]
So is `Runtime.consoleAPICalled` just a temporary workaround for this issue, or is `Log.entry` still the way to go in the future?

**Comment by paulirish** [comment]
Thanks @pthieu and @samir-mahendra for digging into this. Looks correct.

Looks like for completeness one may want to listen to a number of different events:

- `Log.entryAdded` - Logs coming from within the browser
- `Runtime.consoleAPICalled` - A method from the public `window.console` API was called, including `console.log`
- `Runtime.exceptionThrown` - All javascript exceptions/errors. Note: `Runtime.exceptionRevoked` called if a promise rejection was unhandled but now, asynchronously was handled.
- A few more things around network activity: pending/complete XHRs, blocked requests, bad mime type,  set-cookie errors... These are manually issued clientside (and not explicitly over the protocol).

FWIW you can see these listeners being setup in devtools' [consoleModel.js](https://github.com/ChromeDevTools/devtools-frontend/blob/0391fe554b7036c4355b104faadf08885cbd78ad/front_end/console_model/ConsoleModel.js#L65-L111).

**Comment by paulirish** [comment]
This will be fixed by https://chromium-review.googlesource.com/c/chromium/src/+/744729
