### ISSUE TITLE
Add BackendNodeId param to the DOM.querySelectorAll method

### ISSUE THREAD

**Issue by andrenhumi** [ChromeDevTools/devtools-protocol#50]
We currently can only call DOM.querySelectorAll with NodeIds. We'd like to use backendnodeid instead so we can use querySelectorAll directly from a getSnapshot document or even using the root (0) backendnodeid.

Note that evaluating javascript does not give us the same as calling querySelectorAll: if we want to find a node inside an iframe coming from another source, we get a cross site scripting error. So we are only left with querySelectorAll here.

As a follow-up feature request, it would also be great to implement the piercing of iframe boundary and shadow DOM directly using arrays of selectors instead of making several calls with a single selector string.

**Comment by dgozman** [comment]
@pavelfeldman thoughts?

**Comment by andrenhumi** [comment]
gentle ping, any update on this?

**Comment by pavelfeldman** [comment]
Sorry, this fell through the cracks. We don't have a great solution to this atm. Snapshot is atomic, it does not operate node ids. We could introduce `querySelectorAll` next to `getSnapshot` that would only operate backend ids. That is fairly low in the priority list though, do you have anyone who could implement it in mind? It would be adding a method [here](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/inspector/InspectorDOMSnapshotAgent.cpp?sq=package:chromium&l=93).

**Comment by pavelfeldman** [comment]
There has not been much of an update on this one. I would still encourage you to traverse frames and run querySelectorAll in them. The reason we can't do querySelectorAll by backendNodeId is that the nodes we return would need to have nodeIds, which means full blown DOM domain functionality we would want to work around.

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
