### ISSUE TITLE
Page.captureScreenshot partial page screenshot

### ISSUE THREAD

**Issue by bmikkelsen22** [ChromeDevTools/devtools-protocol#51]
I am using the chrome devtools protocol to capture a screenshot of part of a page. In the documentation, there is an optional `clip` parameter listed for the `Page.captureScreenshot` call, which is supposed to only take a screenshot of the specified part of the page. 

However, even when I pass a value for the `clip` parameter, the entire page's screenshot is returned. 

Is this an issue with my code/understanding of the documentation, or could this be an error? I am using chrome beta 61 by the way. 

Here's my code: 
https://gist.github.com/bmikkelsen22/8510c05a0dec4de1001b10f99074aace#file-screenshot-ts-L73
Thanks!

**Comment by pavelfeldman** [comment]
Check out how this is implemented in puppeteer: https://github.com/GoogleChrome/puppeteer/blob/master/lib/Page.js#L484

**Comment by aslushnikov** [comment]
Permalink: [Page.js#L484](https://github.com/GoogleChrome/puppeteer/blob/46115f91829a1bb7da46b51c604ca62ba0bce7e3/lib/Page.js#L484)
