### ISSUE TITLE
Unclear explanation of Target.getTargets vs requesting localhost:9222/json

### ISSUE THREAD

**Issue by michaelfward** [ChromeDevTools/devtools-protocol#52]
The documentation is unclear regarding the difference between response to a GET request pointed at localhost:9222/json and the response to sending a WS frame with JSON data `{"method": "Target.getTargets"}`.

What exactly is different about them? When should you use one or the other?

FWIW, I also asked this question on SO, but figured it might be worthwhile to submit an issue in order to clarify the docs if others find it confusing as well.

[SO question](https://stackoverflow.com/questions/45946173/devtools-protocol-whats-the-difference-between-target-gettargets-and-requestin)

**Comment by aslushnikov** [comment]
@michaelfward the target domain is a modern and recommended way to explore targets. It also allows to communicate with multiple targets only a single connection.

The `/json` endpoint is an old way to explore and connect to targets.
