### ISSUE TITLE
使用Page.captureScreenshot截屏，网页乱码的问题

### ISSUE THREAD

**Issue by VonJie** [ChromeDevTools/devtools-protocol#53]
本地测试完美
![image](https://user-images.githubusercontent.com/13558164/29910040-f369f6e8-8e5a-11e7-9251-1cf9ebaf9ca6.png)
放服务器上后的截屏
![image](https://user-images.githubusercontent.com/13558164/29910004-db03ccc8-8e5a-11e7-844b-a78faaf0beaf.png)
看[接口文档](https://chromedevtools.github.io/devtools-protocol/)也没有设置页面编码的方法
修改系统语言en_US.UTF_8为zh_CN.UTF-8依然无效

**Comment by sseen** [comment]
原来是没有安装中文字体

> `sudo apt-get install fonts-wqy-zenhei`
