### ISSUE TITLE
initiator incorrect in Network.requestWillBeSent

### ISSUE THREAD

**Issue by estuetzel** [ChromeDevTools/devtools-protocol#56]
I am accessing the DevTools API (from Java) and seeing different behavior for the initiator field in Network.requestWillBeSent compared to the behavior in the DevTools Front End. I sniffed the DevTools Front End and the initiator is specified properly in the requestWillBeSent event, however the json from the Java websocket is different when used outside of the DevTools Front End. Most of the time the initiator is the same and matches what is in DevTools Front End, but with some images, it does not match the DevTools Front End. This particular image is added by an element.appendChild dom call (I have set DOM.enable()). Any idea why DevTools Front End gets the right initiator but it's wrong elsewhere?

Below are json snippets for the same image url, first is what I see from Java websocket, and latter is from sniffing DevTools Front End.

```
{
  "method": "Network.requestWillBeSent", ...,
    "initiator": {
      "type": "other"
    },
    "type": "Other"
  }
}
```

```
{
  "method": "Network.requestWillBeSent", ...,
    "initiator": {
      "type": "script",
      "stack": {
        "callFrames": [
          
        ],
        "parent": {
          "description": "Image",
          "callFrames": [
            {
              "functionName": "doWriteImage",
              "scriptId": "38",
              "url": "http://mycomp.com/js/write-image-function.js",
              "lineNumber": 6,
              "columnNumber": 9
            },
            {
              "functionName": "window.onload",
              "scriptId": "39",
              "url": "http://mycomp.com/js/write-image.js",
              "lineNumber": 1,
              "columnNumber": 4
            }
          ]
        }
      }
    },
    "type": "Other"
  }
}
```
[write-image-function.js.txt](https://github.com/ChromeDevTools/devtools-protocol/files/1304609/write-image-function.js.txt)

**Comment by paulirish** [comment]
I doubt that the initiator value is changing based on the type of protocol client. 

I bet a  forced layout is adding non-determinism to your run. Here's the scenario that's likely applying: https://github.com/GoogleChrome/lighthouse/pull/3162#discussion_r138229021

**Comment by estuetzel** [comment]
I don't think the initiator value would be changing for a different client either, but I think there must be something different about what the DevTools Front End is doing. It doesn't make sense to me why the Network.requestWillBeSent events differ anytime I'm using my own client, however consistently that is what I am observing. I don't think it is related to CSS/layout. This is a test html page with a few lines of javascript and one image, no CSS. 
http://counseller-fetch-78104.bitballoon.com/test-write-image-from-script
If you inspect the page with the DevTools Front End, you get the right initiator. I tested again, in the same Chrome session that got the correct initiator, (cleared the cache). This time with a Pyhton client [(PyChromeDevTools).](https://github.com/marty90/PyChromeDevTools) I get the same incorrect result, the initiator for the image is still 'Other'.

```
>>> import PyChromeDevTools
>>> chrome = PyChromeDevTools.ChromeInterface()
>>> chrome.Network.enable()
{u'id': 1, u'result': {}}
>>> chrome.Page.navigate(url="http://counseller-fetch-78104.bitballoon.com/test-write-image-from-script")
{u'id': 2, u'result': {u'frameId': u'42272.1'}}
>>> m = chrome.pop_messages()
>>> import json
>>> j = json.dumps(m)
```
See the initiator for the bishop.png requestWillBeSent event.

**Comment by JoelEinbinder** [comment]
What domains do you have enabled?

**Comment by estuetzel** [comment]
I did just have these three enabled: DOM, Page, Network and Runtime. But I just tried enabling all domains (~22 that can be enabled), and I still get the 'Other' initiator.

**Comment by paulirish** [comment]
@allada is about to comment but try turning on `Debugger.setAsyncCallStackDepth` with a maxDepth of 32.

**Comment by allada** [comment]
I think the problem is with async call stacks. Recently this was enabled by default, but I think the protocol commands are still being sent to enable the depth to use. Even though this lives in the Debugger domain, Network gets a callstack the same way breakpoints do, so when jumping threads even for network requests the Debugger domain will have some influence over the output of the callstacks that Network gets.

If this does not work post a link to the websocket dumps for both devtools front-end and your Java usage and we can probably help more :-)

**Comment by estuetzel** [comment]
`Debugger.setAsyncCallStackDepth` did the trick. Thanks @allada and @paulirish!

**Comment by paulirish** [comment]
@estuetzel Cheers. you've been a champ at debugging this issue. :)

cc @patrickhulce because `initiator`

**Comment by martinalderson** [comment]
If anyone is stuck with this, I had to also do Network.setAttachDebugStack: true to get this working.

**Comment by paulirish** [comment]
> If anyone is stuck with this, I had to also do Network.setAttachDebugStack: true to get this working.

Hmm. That does sounds convincing... but I'm not sure. (Disclaimer: I didnt work on this and didn't know it existed till today. :)

Here's the explainer introducing `Network.setAttachDebugStack` https://docs.google.com/document/d/1WJcNA9PymdWQXOZ4b0xSPmqQCDplWO6c01Ve47lQ2xo/edit

In my experiments I can confirm it affects the async callstack you see in debugger. (Sources), But the initiator appears to be unchanged (in both the Network panel UI and in `Network.requestWillBeSent` event.)

(Given this is probably doesn't belong in the `Network` domain.. but.. I guess too late for that).

Regardless, I'm glad you posted about this. ;)

**Comment by martinalderson** [comment]
Ah, maybe I'm wrong. I tried a lot of things and resorted to copying various things I saw from protocol monitor in dev tools to this so I can't be sure that this was it, but chrome devtools was definitely sending this when I looked at it.
