### ISSUE TITLE
Incorrect screenshot dimensions

### ISSUE THREAD

**Issue by positlabs** [ChromeDevTools/devtools-protocol#57]
I'm using puppeteer to interface with CDP. I am guessing it's not an issue with puppeteer, so I'm filing here. 

I'm attempting to use chrome as a video renderer. It takes a screenshot of the page at a specific resolution (e.g. 1280x544) and then requests the next frame. 

**Issue 1: randomly output 800px width**

This is working ok, except when I try to use clip to get the correct size. It will occasionally save out an image that is 800x544. 

```
await page.screenshot({
    path: filepath,
    clip: {
        x: 0, y: 0,
        width: 1280, height: 544
    }
})
```

**Issue 2: consistently output extra 56px height**

The 800px issue doesn't happen when I capture the whole page, but something else unexpected occurs. I get an image with an extra 56px of white space at the bottom, which makes the screenshots 1280x600. This isn't what I need, but at least it's consistently wrong. 

```
await page.screenshot({
    path: filepath,
    fullPage: true,
})
```

I have opened chromium with some flags: `--window-size=1280,544 --no-first-run'` but still have the extra blank region.

I'm running this process on a node docker image (node:8.4)

**Comment by dgozman** [comment]
It's better to file an issue against Puppeteer if you are using it, since that provides more context and may benefit more users who look for already answered questions when using Puppeteer.

Adding @aslushnikov from Puppeteer.

**Comment by paulirish** [comment]
closing in favor of pptr bugs
