### ISSUE TITLE
Change Network Response.status from number to integer?

### ISSUE THREAD

**Issue by mafredri** [ChromeDevTools/devtools-protocol#58]
This is true for both `Response` and `WebSocketResponse` in the Network domain, their `status` properties are of type `number` instead of `integer`. Could they be changed to `integer` (as per HTTP spec) or is there something that relies on them being `number`s?

The reason I'm asking is that I maintain a Go library for the protocol (cdp) where typed code is generated from the protocol definition and the distinction is useful. In https://github.com/mafredri/cdp/issues/27 a user asked why this wasn't an `int`, reasonably so.

Is there anything I can do to help get this changed?

**Comment by allada** [comment]
Thanks, I have sent a patch to address this here: https://chromium-review.googlesource.com/c/chromium/src/+/676504

**Comment by allada** [comment]
Fixed. See http://crbug.com/767274

Thanks for the report!

**Comment by mafredri** [comment]
Awesome, thanks for the prompt fix!
