### ISSUE TITLE
Add some way to set `navigator.language/.languages`

### ISSUE THREAD

**Issue by Jamesernator** [ChromeDevTools/devtools-protocol#59]
I've been using puppeteer for website testing, however something that the devtools protocol doesn't support (and hence puppeteer can't support either) is setting the expected user language(s), this makes it impossible to automatically test translated forms of the website that rely upon those interfaces to detect user language.

Based upon the existence of `Emulation.setGeolocationOverride` I'd imagine this should be doable with a similar API.

**Comment by dgozman** [comment]
We already have `Emulation.setNavigatorOverrides`, just need to add `language` there. Filed a [chromium bug](https://crbug.com/767270).

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
