### ISSUE TITLE
Feature Request: Save an image from the DOM to disk

### ISSUE THREAD

**Issue by adrianseeley** [ChromeDevTools/devtools-protocol#60]
A feature to save an `<img>` tag `src` or a stylesheet applied `background-image url` would be awesome.

**Comment by kdzwinel** [comment]
Not sure what's your use case, but if you have an URL to a resource, you shouldn't need DT protocol to download it, right?
And even if, for some reason, you can't download it you should be able to:
- base64 encode it in the browser context and get it via Runtime.evaluate or
- make a screenshot of it using Page.captureScreenshot.

**Comment by paulirish** [comment]
⬆️   aye, what konrad said, mostly..

the DT protocol is a bit lower level so it wont' offer a feature like this. 

`Page.getResourceContent` is your best bet aside from what konrad offered.
