### ISSUE TITLE
document base for setDocumentContent?

### ISSUE THREAD

**Issue by jmjpro** [ChromeDevTools/devtools-protocol#61]
Can I use relative urls in html that I pass to setDocumentContent()? If so, how is the document base determined?

**Comment by paulirish** [comment]
here's the start of the setDocumentContent impl: https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/inspector/InspectorPageAgent.cpp?type=cs&q=setDocumentContent+f:agent&sq=package:chromium&l=680

it is basically the same as `document.open(), document.write(html), document.close();`

as such the document's location isn't changed, so you're still dealing with whatever URL the page had when loaded.

**Comment by jmjpro** [comment]
hi @paulirish I think you misunderstood my question. Perhaps this isn't a question for the dev tools protocol but for data URLs in general: I'm passing HTML like this

`data:text/html,<html><body><img src="clock.svg"></body></html>`

Is a relative link to an image meaningless in the context of a data URL?
