### ISSUE TITLE
Error calling Network.getResponseBody

### ISSUE THREAD

**Issue by ghost** [ChromeDevTools/devtools-protocol#64]
I listen for Network.responseReceived events and follow up with Network.getResponseBody. Usually the response body comes back fine no problem. However, if the response is a downloaded file, it seems getResponseBody returns an error, 'No data found for resource with given identifier'. I'm not sure if this is intentional or not? Are certain response bodies not permitted through the API? Just to be clear, this file shows up in the download bar at the bottom of Google Chrome. It does not show up in the Network tab in the inspector, but there are still the usual Network events fired for the file. 

```
{"method":"Network.getResponseBody","params":{"requestId":"26994.2"},"id":17}
Network.getResponseBody: {"error":{"code":-32000,"message":"No data found for resource with given identifier"},"id":17}
```

That call and response both follow these two usual events which precede a working getResponseBody invocation:
```
{
  "method": "Network.requestWillBeSent",
  "params": {
    "requestId": "26994.2",
    "loaderId": "26994.2",
    "documentURL": "http://counseller-fetch-78104.bitballoon.com/com.test.any.apk",
    "request": {
      "url": "http://counseller-fetch-78104.bitballoon.com/com.test.any.apk",
 ...
    "type": "Document",
    "frameId": "26994.1"
  }
},
{
  "method": "Network.responseReceived",
  "params": {
    "requestId": "26994.2",
    "loaderId": "26994.2",
    "timestamp": 1395971.150643,
    "type": "Document",
    "response": {
      "url": "http://counseller-fetch-78104.bitballoon.com/com.test.any.apk",
      "status": 200,
      "statusText": "OK",
...
    "frameId": "26994.1"
  }
}
```

**Comment by estuetzel** [comment]
Here you can recreate [PyChromeDevTools](https://github.com/marty90/PyChromeDevTools)

```
import PyChromeDevTools, time
c = PyChromeDevTools.ChromeInterface(port=9228)
c.Page.enable()
c.Network.enable()
c.Page.navigate(url="http://counseller-fetch-78104.bitballoon.com/download-apk")
time.sleep(3)
messages = c.pop_messages()

el = [x for x in messages if x['method'] == "Network.responseReceived" and x['params']['response']['url'] == 'http://counseller-fetch-78104.bitballoon.com/com.test.any.apk'] [0]

c.Network.getResponseBody(requestId=str(el['params']['requestId']))
#response is: {"error":{"code":-32000,"message":"No data found for resource with given identifier"},"id":4}
```

**Comment by paulirish** [comment]
cc @eugeneo

**Comment by bendem** [comment]
I'm having the same problem, was there ever a solution for this?

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
