### ISSUE TITLE
What is Javascript object id parameter of DOM.requestNode

### ISSUE THREAD

**Issue by cezarypiatek** [ChromeDevTools/devtools-protocol#66]
I'm trying to invoke DOM.ReqestNode function to extract nodeId but I was unable to figure out what is "JavaScript object id". How can I get it?

**Comment by aslushnikov** [comment]
Given a remote object, pointing to the DOM element, the method will push all DOM nodes that lay on the path from root to the given node.

Hope this helps!

**Comment by cezarypiatek** [comment]
Not even a little bit. How can I get this  "JavaScript object id" ?

**Comment by aslushnikov** [comment]
@cezarypiatek ah, these are ids of [RemoteObject](https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#type-RemoteObject) type. RemoteObjects can be obtained by running [Runtime.evaluate](https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#method-evaluate) method.

**Comment by cezarypiatek** [comment]
Thanks, but Runtime.evaluate is even more cryptic. Can I get a full example how to get this id for given DOM node (for example based on xpath or other css selector)?

**Comment by aslushnikov** [comment]
@cezarypiatek sure

```js
const { exceptionDetails, result: remoteObject } = await protocol.send('Runtime.evaluate', {
  expression: 'document.querySelector(".container")'
});
console.log(remoteObject.objectId);
```

Also, feel free to explore how puppeteer uses protocol to work with remote objects: [Puppeteer/ExecutionContext.js](https://github.com/GoogleChrome/puppeteer/blob/master/lib/ExecutionContext.js)

**Comment by cezarypiatek** [comment]
This is exactly what I was looking for. Thanks for help @aslushnikov

**Comment by cezarypiatek** [comment]
@aslushnikov  I'm getting weird value as a objectId from Runtime.evaluate

```
{"injectedScriptId":1,"id":1}
```

What am I doing wrong?

**Comment by deepnov** [comment]
> @cezarypiatek sure
> 
> ```js
> const { exceptionDetails, result: remoteObject } = await protocol.send('Runtime.evaluate', {
>   expression: 'document.querySelector(".container")'
> });
> console.log(remoteObject.objectId);
> ```
> 
> Also, feel free to explore how puppeteer uses protocol to work with remote objects: [Puppeteer/ExecutionContext.js](https://github.com/GoogleChrome/puppeteer/blob/master/lib/ExecutionContext.js)

Hi.. will you be able to guide me how an elementHandle object  can be used with the Runtime.evaluate method to get the objectId?

**Comment by cezarypiatek** [comment]
Sorry, It was 6y ago, I don't remember anything from this stuff.
