### ISSUE TITLE
[docs] Clarify `Page.Viewport` `x` and `y` properties

### ISSUE THREAD

**Issue by joshsleeper** [ChromeDevTools/devtools-protocol#67]
# problem
The `description`s for the `x` and `y` properties on `Page.Viewport` are sufficiently vague in the context of `Page.captureScreenshot.clip` that the Puppeteer team made the mistake of interpreting them as x and y values for the __element__ relative to the __current viewport__.

Unfortunately, they are actually used in Chromium as x and y values for the __viewport__ relative to the __document__.

# solution
I would suggest clarifying the `description` strings for these properties.

# relevant code
### Puppeteer issue describing the problem
https://github.com/GoogleChrome/puppeteer/issues/1315

### Puppeteer PR to resolve the mistake
https://github.com/GoogleChrome/puppeteer/pull/1323

### Chromium usage
https://github.com/ChromeDevTools/devtools-protocol/blob/master/json/browser_protocol.json#L262-L263

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
