### ISSUE TITLE
Missing beforeExecuting event and line shift property during eval in debugger api

### ISSUE THREAD

**Issue by Alphapage** [ChromeDevTools/devtools-protocol#68]
Hello,

I try to use the debugger protocol to get the inline sourcemap from an dynamically invoked script `eval` .
I tried `scriptParsed `event, but it seems to not wait for the end of the callback to start executing.
During `eval`, we need to get the inline sourcemap to set breakpoints according to the authored source file before let chrome execute the script.
The other problem I found is that chrome adds `(function(){` at the beginning of the script which shifts by 1,2 or more lines depending on the parameters length (and maybe column shift too). Without such a property, it is difficult to map from authored source, generated source and chrome generated source with line shift.

Could you help to solve those problems ?

Thank you in advance for your help.

**Comment by ak239** [comment]
You can pause script execution by using `Debugger.setBreakpointByUrl({lineNumber: 0, urlRegex: ".*"})`. Once paused you can setup everything and then use `Debugger.resume` to resume execution.
For `new Function("...")` Chrome adds `(function(){` by JavaScript spec. For inline event listeners there is open issue: [crbug.com/70895](crbug.com/70895). I believe that in other case Chrome does not append anything to source. Could you share details where you see `(function(){` prefix?

**Comment by Alphapage** [comment]
> You can pause script execution by using Debugger.setBreakpointByUrl({lineNumber: 0, urlRegex: ".*"}). 

I tried without success for `eval`. I willl try again: maybe I forget something.
Chrome only append when using `new Function` in script: if you getScriptSource from the `eval` scriptId in scriptParsed then you will find the appended `(function(){`.
From there, it could  be solved by adding a line shift property, but a better way would let chrome to align to original script, so breaking at 0:0 will stop at the first line of the original script not the chrome  surrounded one.

**Comment by ak239** [comment]
Oh, my bad. `Debugger.setBreakpointByUrl` will work only for evals with sourceURL and I think we do not provide any way to break before any eval. We have a bug for this as well: [crbug.com7724793](crbug.com724793).
I am not sure what eval you use. Is it regular JavaScript eval in page context or some protocol command?

**Comment by Alphapage** [comment]
No problem. 
I tried with sourceURL without success.
For info, I tried on nodejs 8.9.
I will give it a try with a browser page to see the difference.
'instrumentation' is only for DOMDebugger as far as I understand. We should be able to break before the script loads as well in Debugger api. Don't you think so ?

**Comment by Alphapage** [comment]
I tried with a browser page and the problem remains the same.
Even in ChromeDevTools, we need to refresh the page to get the sourcemap working because of this missing feature.
For now, it is impossible to debug an `eval` script with inline sourcemaps.

**Comment by Alphapage** [comment]
I think 

> You can pause script execution by using Debugger.setBreakpointByUrl({lineNumber: 0, urlRegex: ".*"}). 

is a poor workaround to solve problems: it requires to deal with users and internal breakpoints because the user can add a breakpoint at line:0 too.
It would be better to assign breakpoints api to user only (ide) and provide other api to manage internal workflow.
But this is just my opinion.

**Comment by ak239** [comment]
We can introduce something like `Debugger.setPauseOnScriptFirstStmt` but I would like to understand our use case better and consider all different options. Since in example with inline source map, alternative solution can be parsing source map on backend side without any kind of new protocol API.
I am not sure what do you mean by internal workflow. IDE can be interested in parsing source maps as well. Another valid use case is way to preprocess all parsed scripts: set pause on script first stmt and then use `Debugger.setScriptSource` on every `scriptParsed` event.

**Comment by Alphapage** [comment]
I use inline sourcemaps because they are generated dynamically at runtime.
I think it is the goal of inline sourcemaps and it doesn't polute a backend folder with unnecessary files.

Your first option seems easier to understand if you add the reason to paused event and manage the user at 0:0 if requested as well (double pause at the same location with different reason, but this can be manages by the debugger client too: it is your choice ;-) ).
It is unclear for the second option: you won't be able to parse script generated dynamically in this case: but maybe I'm wrong.

**Comment by Alphapage** [comment]
Hello @ak239 ,
Any news about such a feature:
- is it under discussion ?
- do you think about implementing quickly in Chrome devtools ?
I hope you will have time to work on this problem.

**Comment by Alphapage** [comment]
Any more info ? It seems  I'm the only one to want such a feature to be implemented.

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
