### ISSUE TITLE
pushNodesByBackendIdsToFrontend aways return { nodeIds: [ 0, 0, 0, 0, 0, ... ] }

### ISSUE THREAD

**Issue by jasonChen1982** [ChromeDevTools/devtools-protocol#7]
when i use pushNodesByBackendIdsToFrontend to mapping backendIds to frontendIds,but aways get { nodeIds: [ 0, 0, 0, 0, 0, ... ] }

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
