### ISSUE TITLE
github pages - bottom of the left menu is out of window

### ISSUE THREAD

**Issue by gsouf** [ChromeDevTools/devtools-protocol#70]
Hi,

When navigating on the doc hosted on github pages the left menu is not reachable and last items cannot be clicked.

See :

![cdp1](https://user-images.githubusercontent.com/3215399/32942670-03dabb36-cb8a-11e7-859e-fd3115751dfc.PNG)

Expected result:

![cdp2](https://user-images.githubusercontent.com/3215399/32942680-09971628-cb8a-11e7-8597-a1a7c6f555d5.PNG)

**Comment by kdzwinel** [comment]
Thanks for reporting! I'm moving this issue to a repo where we track website issues: https://github.com/ChromeDevTools/debugger-protocol-viewer/issues/92
