### ISSUE TITLE
modifiers not working with dispatchKeyEvent 

### ISSUE THREAD

**Issue by Jip-Hop** [ChromeDevTools/devtools-protocol#74]
I'm trying to send the keyboard shortcut `command + i` or `control + i` using the devtools-protocol from Node.js with [chrome-remote-interface](https://github.com/cyrus-and/chrome-remote-interface).

Sending the `i` keystroke is no problem with this code:
```
const CDP = require('chrome-remote-interface');

CDP((client) => {
    // extract domains
    const { Network, Page } = client;

    client.Input.dispatchKeyEvent({
        "modifiers": 0,
        "text": "i",
        "type": "keyDown"
    });

}).on('error', (err) => {
    // cannot connect to the remote endpoint
    console.error(err);
});
```

But for some reason the modifiers don't do anything... I've tried values of 2 and 4 for the modifiers, but that didn't do anything. I've also tried a value of 8 to see if I'd get a capital letter `I` in an input field, but no luck.

With this [online keystroke tester](http://unixpapa.com/js/testkey.html) I get the following result:
```
keydown  keyCode=0         which=0         charCode=0        
keypress keyCode=105 (i)   which=105 (i)   charCode=105 (i)  
```
Regardless of the modifier value used...
How can I send the keyboard shortcut `command + i` or `control + i`?

**Comment by JoelEinbinder** [comment]
The shift modifier doesn’t make the letter capital. Consider if the use had capslock and shift presssed. It would be a lowercase i with shiftKey set to true. What’s the ctrlKey and metaKey values for the events you are seeing in the page?

**Comment by Jip-Hop** [comment]
Perhaps I misunderstood the purpose of modifier keys. But I'm trying to invoke the control + i keyboard shortcut on Google Earth: https://earth.google.com/web

I can't find documentation or examples on how to do this (sending keyboard shortcuts involving multiple keys) using the devtools protocol. I thought that's what the modifier property is for.

Do you know how to send the control + i key combination?

**Comment by JoelEinbinder** [comment]
I'd try:
```
{
   "modifiers": 2,
   "text": "i",
   "unmodifiedText": "i",
   "key": "i",
   "code": "KeyI",
   "windowsVirtualKeyCode": 73,
   "type": "keyDown"
}
```

You can take a look at how we do it in Puppeteer: https://github.com/GoogleChrome/puppeteer/blob/master/lib/Input.js

**Comment by Jip-Hop** [comment]
Great! Thanks for the example. It's working now. Had no idea I had to fill out all those attributes. Found [USKeyboardLayout.js](https://github.com/GoogleChrome/puppeteer/blob/master/lib/USKeyboardLayout.js) to be very helpful too.

I actually came across Puppeteer before but had to use the DevTools protocol directly since Puppeteer doesn't have [Page.setGeolocationOverride](https://github.com/GoogleChrome/puppeteer/pull/1297) implemented yet.
