### ISSUE TITLE
deprecate headerTemplate and footerTemplate of Page.printToPDF in favour of web standards https://www.w3.org/TR/css3-page/

### ISSUE THREAD

**Issue by graingert** [ChromeDevTools/devtools-protocol#75]
Instead of proprietary hacks, printing should use and improve existing web standards: https://www.w3.org/TR/css3-page/

**Comment by InkUisitor** [comment]
Can we have more vision about this issue to know how we will work with the footer and header parts ?
The question has been asked 3 month before. Thanks

**Comment by paulirish** [comment]
It probably _should_ use paged media, yes.. But I don't expect the method to change anytime soon. Sorry!
