### ISSUE TITLE
Is there a way to access Browser Dialogs (not Page Dialogs) ?

### ISSUE THREAD

**Issue by simov** [ChromeDevTools/devtools-protocol#76]
:wave: 

I'm writing tests for my Chrome extension using Puppeteer and I was wondering if there is a way intercept the browser's pupup dialogs, like the one that pops up when you [request new permission](https://developer.chrome.com/apps/permissions#method-request) for your extension. The other way around wound be to disable the browser popups with a chrome flag and accept them by default, but I can't find such flag either.

**Comment by paulirish** [comment]
No those extension dialogs are not currently plumbed through to the devtools protocol.

**Comment by simov** [comment]
I ended up using a test `manifest.json` file that contains the needed permissions set as required ones. I have an options page in my extension for managing the allowed origins, and in this case only the removing of permissions (origins) can't be tested, because they are required. Required or previously added permissions does not trigger the consent popup when requested.

**Comment by paulirish** [comment]
Sounds good to me! Nice one.
