### ISSUE TITLE
Is there a way to intercept the entire redirect chain in popup?

### ISSUE THREAD

**Issue by Dry7** [ChromeDevTools/devtools-protocol#77]
When I click on a page http://getresto.gifts48.ru/1/

A window opens with the following redirect chain:

http://getresto.gifts48.ru/1/popup1.php
http://getresto.gifts48.ru/1/popup2.php
http://getresto.gifts48.ru/1/popup3.php
http://getresto.gifts48.ru/1/popup4.php
http://getresto.gifts48.ru/1/popup5.html
http://getresto.gifts48.ru/1/popup6.html
http://getresto.gifts48.ru/1/popup7.html
http://getresto.gifts48.ru/1/popup8.html

I'm trying to collect this chain with this code

https://gist.github.com/Dry7/6ef5d8e363eb8ee05d833ca5d72cc5dd

But the first three pages are missing.
How can I fix this?

One solution would be to use Target.setAutoAttach, but it is simply ignored.

**Comment by paulirish** [comment]
See answer here: https://groups.google.com/forum/#!topic/chrome-debugging-protocol/n1FQ4Ypww6w

> Target.setAutoAttach does not work on popups.
> Unfortunately, currently there is no way to attach early enough to not miss first network requests. We are working on it though.

**Comment by Niek** [comment]
+1 -  as far as I can see it's not possible to work around this, I tried``Page.waitForDebugger()`` and ``Network.setRequestInterception()`` without success.

**Comment by route** [comment]
It's now huge pain to work with windows on Chrome

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!

**Comment by Niek** [comment]
Opened a bug report here: https://bugs.chromium.org/p/chromium/issues/detail?id=1070568
