### ISSUE TITLE
Unable to display element CSS

### ISSUE THREAD

**Issue by jankoritak** [ChromeDevTools/devtools-protocol#78]
I'm trying to display element styles for node with `nodeId` using devtools-protocol

When element is clicked I receive 4 messages in total

- CSS.getMatchedStylesForNode
- CSS.getComputedStyleForNode
- CSS.getPlatformFontsForNode
- CSS.getPlatformFontsForNode

to which I respond (I think) correctly, yet styles are not visible in dev-tools panel

![devtools-panel](https://user-images.githubusercontent.com/5691407/34818518-4f9bc176-f6bb-11e7-9836-e72ad6a1a447.png)

Detailed communication:

Requests:

- `{"id":35,"method":"CSS.getMatchedStylesForNode","params":{"nodeId":80}}`
- `{"id":36,"method":"CSS.getComputedStyleForNode","params":{"nodeId":80}}`
- `{"id":37,"method":"CSS.getPlatformFontsForNode","params":{"nodeId":80}}`
- `{"id":38,"method":"CSS.getInlineStylesForNode","params":{"nodeId":80}}`

Responses. (Were too long, so I shorted them, CONTENT is a placeholder for their content)

- `{"result":{"cssKeyframesRules":[],"inherited":[{ CONTENT }],"id":35}`
- `{"result":{"computedStyle":[{ CONTENT }],"id":36}`
- `{"result":{"fonts":[]},"id":37}`
- `{"result":{"inlineStyle":{"cssProperties":[],"cssText":"","range":{"endColumn":0,"endLine":0,"startColumn":0,"startLine":0},"shorthandEntries":[],"styleSheetId":"69061.90"}},"id":38}`

I would love to hear any pointer in the direction of a solution, been stuck on this for days,

Thanks!

**Comment by aslushnikov** [comment]
@jankoritak can you open devtools-on-devtools and check if there are any errors?

**Comment by jankoritak** [comment]
Hi @aslushnikov,

thanks for the quick reply. Sure, here is a screen. Somehow managed to overlook that till now.

Could you help me interpret the error?

![screen shot 2018-01-11 at 11 43 03](https://user-images.githubusercontent.com/5691407/34821629-b18f16fe-f6c4-11e7-85a0-5fee82876bd8.png)

**Comment by aslushnikov** [comment]
@jankoritak ah, this explains everything. Take a look at this code in the devtools frontend: [SDK.CSSRule](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/devtools/front_end/sdk/CSSRule.js?type=cs&q=CSSRule&sq=package:chromium&l=39)

If the payload you report in `getMatchedStyles` includes `styleSheetId`'s, then you should also report the stylesheet with this id to the front-end. You should emit the `CSS.styleSheetAdded` event for that.

**Comment by jankoritak** [comment]
Thanks @aslushnikov, that makes perfect sense. It works now as expected.

So far, I've looked only into dev-tools-protocol specification, so my view on the problematics is really narrow. Could you also point me to the code that transforms dev-tools-protocol messages to frontend SDK calls?

Thanks

**Comment by aslushnikov** [comment]
> Could you also point me to the code that transforms dev-tools-protocol messages to frontend SDK calls?

@jankoritak Sure. (almost) Every domain has associated SDK model class. CSS model is very  representative: [SDK.CSSModel](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/devtools/front_end/sdk/CSSModel.js) is associated with CSS domain.

CSSModel registers dispatcher with `registerCSSDispatcher`. DIspatcher handles protocol events and forwards them to the model for processing.

**Comment by jankoritak** [comment]
Great, thanks! Much appreciate the help.

Closing the issue.
