### ISSUE TITLE
Protocol Browser - 404 on all resources

### ISSUE THREAD

**Issue by theduke** [ChromeDevTools/devtools-protocol#79]
The browser currently shows only 404s for all resources, inlcuding head, stable1.2 and stable1.3:

https://chromedevtools.github.io/devtools-protocol/

Is there any other resource for how the protocol looks like?

**Comment by kdzwinel** [comment]
I can't reproduce it. Can you please let us know what browser you are using?

**Comment by kdzwinel** [comment]
Moving to protocol viewer repo: https://github.com/ChromeDevTools/debugger-protocol-viewer/issues/100
