### ISSUE TITLE
CSS.getStyleSheetText documentation incorrect

### ISSUE THREAD

**Issue by rbairwell** [ChromeDevTools/devtools-protocol#80]
According to https://chromedevtools.github.io/devtools-protocol/tot/CSS#method-getStyleSheetText : 
"Returns the current textual content and the URL for a stylesheet."

however, the return object is just:
"RETURN OBJECT
text
string
The stylesheet text."

No URL is returned.

**Comment by paulirish** [comment]
Thanks. A fix will go in with https://chromium-review.googlesource.com/c/chromium/src/+/993477
