### ISSUE TITLE
Planning on restricting navigation to data-urls over CDP?

### ISSUE THREAD

**Issue by auchenberg** [ChromeDevTools/devtools-protocol#82]
Do Chrome plan on restricting navigation to data-urls over CDP, following the simple principle as Mozilla in https://blog.mozilla.org/security/2017/11/27/blocking-top-level-navigations-data-urls-firefox-58/

Asking as Visual Studio today are using `data://` urls to provide an embedded loading page while our debugger is starting.

**Comment by pavelfeldman** [comment]
`Pave.navigate` is considered a browser-initiated navigation in Chrome. This falls into the second bucket of the FF use cases along with the manually pasting this URL into the Omnibox. Hence it will be allowed.

**Comment by auchenberg** [comment]
Great, thanks for clarifying @pavelfeldman

**Comment by dhanvikapila** [comment]
@pavelfeldman  thanks for your reply. One more question regarding the same -  do you think there is any change in thinking on this issue if Chrome is launched with a command line argument containing a `data://` url instead of a `Page.navigate` ?

**Comment by paulirish** [comment]
@dhanvikapila that does also fall into the second bucket of use cases. I didn't check to see if it works or doesn't but I could imagine it may not work for other reasons that are too low-priority to fix. 

But, regardless, you should be able to rely on page.navigate.
