### ISSUE TITLE
Page.printToPDF problem with header and footer templates

### ISSUE THREAD

**Issue by vadger** [ChromeDevTools/devtools-protocol#84]
Hello,

I'm trying to add custom header and footer templates to the document. My request is like:

```javascript
{
displayHeaderFooter: true,
headerTemplate: "<span class=\"title\"></span>",
footerTemplate: "<span class=\"title\"></span>",
}
```

Instead of seeing title in both header and footer I see default header and footer. So it seems that chrome ignores custom values.

Version I use is Google Chrome 64.0.3282.140
API client: https://github.com/wendigo/chrome-reactive-kotlin

Same situation with nodejs CDP library - custom headers/footers are ignored:
```javascript
    const { data } = await client.Page.printToPDF({
      printBackground: true,
      displayHeaderFooter: true,
      headerTemplate: 'TITLE:<span class="title"></span>',
      footerTemplate: 'TITLE:<span class="title"></span>'
    });
```

**Comment by JoelEinbinder** [comment]
It looks like `headerTemplate` was released in 65.

**Comment by vadger** [comment]
Tried with Chrome 65 and event 66 - same behaviour - headerTemplate/footerTemplate are ignored.
