### ISSUE TITLE
Mismatch between certain property enums

### ISSUE THREAD

**Issue by mafredri** [ChromeDevTools/devtools-protocol#86]
Hey,

I've noticed there are some property enums (i.e. not types defined in a domain) that seem like they should be the same, but their actual enum values differ.

I've at least found these in the Runtime domain:

```
PropertyEnum(Runtime.RemoteObject.type)
    [object function undefined string number boolean symbol]

PropertyEnum(Runtime.ObjectPreview.type)
    [object function undefined string number boolean symbol]

PropertyEnum(Runtime.PropertyPreview.type)
    [object function undefined string number boolean symbol accessor]

PropertyEnum(Runtime.RemoteObject.subtype)
    [array null node regexp date map set weakmap weakset iterator generator error proxy promise typedarray]

PropertyEnum(Runtime.ObjectPreview.subtype)
    [array null node regexp date map set weakmap weakset iterator generator error]

PropertyEnum(Runtime.PropertyPreview.subtype)
    [array null node regexp date map set weakmap weakset iterator generator error]
```

Just looking to confirm if this is actually the intended behavior or not.

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
