### ISSUE TITLE
Use Devtools protocol to get the navigation redirect chain

### ISSUE THREAD

**Issue by leem32** [ChromeDevTools/devtools-protocol#87]
How can I get the navigation redirect chain without also getting unwanted urls such as image and ad server urls?

By navigation redirect chain I mean for example when you load website-a.com and that redirects to website-b.com then website-c.org etc I need to get only these redirects.

I've tried using the `Network.requestWillBeSent` event and this does work to get the redirect chain but it also gets lots of other unwanted urls which are not part of the navigation redirect chain. I can filter out most of the unwanted urls by checking for `document` type, but can't figure out how to effectively filter the urls any more.

Also, Why is the initiator param usually `other` for redirect urls? according to the Devtools docs shouldn't it be `redirect`?
Using initiator `other` helps in filtering out more unwanted urls, but some still manage to get through so it's to unreliable to use.

Any help would be greatly appreciated. I've been at this all weekend now. It's driving me insane.

Code example:
```javascript
// chrome-network.js
// Run: 'node chrome-network.js http://mirror.co.uk' to see the problem (with or without initiator filter)

var url = process.argv[2];

const puppeteer = require('puppeteer');

puppeteer.launch().then(async browser => {
  const page = await browser.newPage();
// note: add trailing slash since chrome adds it
if (!url.endsWith('/'))
  url = url + '/';

// urls hold redirect chain
const urls = [url];

const client = await page.target().createCDPSession();
await client.send('Network.enable');
await client.on('Network.requestWillBeSent', (e) => {

  if (e.type !== "Document") {
    return;
  }

  // using other is unreliable
  // try http://mirror.co.uk or http://dailymail.co.uk/
  // if (e.initiator.type !== "other") {
  //   return;
  // }
console.log("EVENT INFO: ");
console.log(e.type);
console.log(e.documentURL);
console.log("INITITIATOR: " + JSON.stringify(e.initiator, null, 4));

  // check if url redirected
  if (typeof e.redirectResponse != "undefined") {

    // // get redirect info
    // console.log("REDIRECT RESPONSE: ");
    // console.log(e.redirectResponse);
    console.log("REDIRECT STATUS CODE: ");
    console.log(e.redirectResponse.status);

    console.log("REDIRECT REQUEST URL: ");
    console.log(e.request.url);
    urls.push(e.redirectResponse.status, e.request.url);

  } else {
    // url did not redirect
    if (e.request.url !== urls[urls.length - 1]) {
      console.log("NO REDIRECT REQUEST URL: ");
      console.log(e.request.url);
      urls.push(e.request.url);
    }
  }
});
  await page.goto(url);
  console.log("Final urls array: ");
  console.log(urls);

  await browser.close();
});
```

**Comment by paulirish** [comment]
I believe this question has been answered in the pptr slack. I'd ask there.

**Comment by geekscrapy** [comment]
Hey @paulirish, I had the same question,  what's pptr? :D

**Comment by kdzwinel** [comment]
@geekscrapy Paul ment https://github.com/GoogleChrome/puppeteer (pptr for short 😉)

**Comment by srozzo** [comment]
@leem32 
``
    // Intercept requests 
    await page.setRequestInterception(true)

    // Request interception handler
    page.on('request', request => {
        // Capture any request that is a navigation requests that attempts to load a new document
        // This will capture HTTP Status 301, 302, 303, 307, 308, HTML, and Javascript redirects    
        // Make sure the redirect is in the parent frame or we will see the navigation for other windows/frames
        var parentFrame = request.frame().parentFrame()
        if (request.isNavigationRequest() && parentFrame === null) {
            o = { url: request.url() }
            redirects.chain.push(o)
        }
        // Continue to next request
        request.continue()
    });
``

**Comment by sts-ryan-holton** [comment]
This doesn't seem to get the URL for a page that might have a `setTimeout` to another page, how can we get `Network.requestWillBeSent` to pick up these pages too?
