### ISSUE TITLE
"Input.setIgnoreInputEvents" blocks both user and generated events.

### ISSUE THREAD

**Issue by vsDizzy** [ChromeDevTools/devtools-protocol#88]
It would be nice to have this command not block generated events, so only debugger could interact with the page. Now user input interferes with "Input.dispatchKeyEvent" and "Input.dispatchMouseEvent". Don't want to use headless, just restrict user input.

**Comment by RichieAHB** [comment]
Or alternatively have something to block input events from the user as a separate flag.

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
