### ISSUE TITLE
"Input.dispatchMouseEvent" does't post to inactive tab.

### ISSUE THREAD

**Issue by vsDizzy** [ChromeDevTools/devtools-protocol#89]
It waits for specified tab to be active. It would be nice to send input to foreground pages as well.

**Comment by paulirish** [comment]
> It would be nice to send input to foreground pages as well.

You mean _background_, right?

I don't think that's possible without massive changes to Chromium. Background pages are background.

**Comment by vsDizzy** [comment]
Yes background.
Actually mouse move event is posted - 1 message per 5 seconds. I had multiple move events chained so it took more than a minute for me.
