### ISSUE TITLE
Is there an api for pull page screenshot?

### ISSUE THREAD

**Issue by msathis** [ChromeDevTools/devtools-protocol#9]
I couldn't find anything related to full page screenshot [here](https://chromedevtools.github.io/debugger-protocol-viewer/tot/Page/).

**Comment by ui4j** [comment]
https://medium.com/@dschnr/using-headless-chrome-as-an-automated-screenshot-tool-4b07dffba79a?1

**Comment by kdzwinel** [comment]
@msathis there is no specific method for that, you have to do what the author of the article suggested by @ui4j does - resize the visible area to accommodate for the whole website and then take a screenshot. That's also how DevTools do it.
Note that this won't work for certain websites (e.g. when `vh` units are used).

**Comment by auchenberg** [comment]
This seems like a good opportunity for a NPM package.

**Comment by westy92** [comment]
I will be implementing this shortly!
https://github.com/westy92/html-pdf-chrome/issues/13

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
