### ISSUE TITLE
[Feature Request] Evaluate inside closure

### ISSUE THREAD

**Issue by bmeck** [ChromeDevTools/devtools-protocol#91]
Sometimes I want to evaluate code while paused or only given a function reference for a closure that is not currently on the call stack. It would be nice to be able to call `evaluate` while passing a function and evaluate code in its outer scope.

Example:

```mjs
// code being debugged
function foo(o) {
  return function bar() {
    return o.x;
  }
}
let g = foo();
g(); // error undefined does not have a property .x
```

```mjs
// pseudo-code while debugging
evaluateInScope(g, 'o') // undefined
evaluateInScope(g, 'o = this', {x: 2}); // let me pass in some kind of parameter
g(); // now 2
```

**Comment by dgozman** [comment]
Does [Debugger.evaluateOnCallFrame](https://chromedevtools.github.io/devtools-protocol/tot/Debugger#method-evaluateOnCallFrame) do the trick?

**Comment by ak239** [comment]
It does only for current function on stack. In this features request we need some way to evaluate expression in context of any function, I actually believe that we can do it not only on pause.

**Comment by bmeck** [comment]
@dgozman as @ak239 said, this is about when I have a reference to a function that is not currently on the stack, so I don't have a `CallFrameId` for the function.

**Comment by dgozman** [comment]
Interesting! We'll have to think about ergonomics of this.
Do you have a particular example/usecase with more details? E.g. if we were to implement this in Chrome DevTools, how do you think the feature should look like to the user?

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
