### ISSUE TITLE
Page.navigate with HTTP POST method and custom headers

### ISSUE THREAD

**Issue by sukhovy** [ChromeDevTools/devtools-protocol#92]
Is it possible to navigate to the page by sending POST request instead of default GET with sending form data and custom headers?

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
