### ISSUE TITLE
Add timestamp to all CRDP messages

### ISSUE THREAD

**Issue by digeff** [ChromeDevTools/devtools-protocol#94]
New feature requested: Add timestamp to all CRDP messages (Timestamp of when the message was sent)
Scenario: We'd like to track the performance of our debugger, to make sure that all responses and notifications from CRDP are processed quickly. To be able to measure this properly it'd be really useful if you could add a timestamp of when the message was sent, to all CRDP messages. That way when we finish processing a notification or response we can calculate how much time the whole pipeline spent reciving and processing that response, and detect any possible performance issues.

**Comment by paulirish** [comment]
cc @dgozman 

This would also help to understand how long messages are queued.

**Comment by dgozman** [comment]
Just curious, are you interested in websockets performance? Because you can grab a timestamp immediately after receiving a websokcet frame - the only difference would be the speed of our websokcets processing, which is probably negligible.

Also note that for command+response, you can have the whole round-trip measured on the client side, matching by message id.

**Comment by digeff** [comment]
We are interested in websockets performance. We are also interested in OS buffering if a lot of messages are being sent, and any other thing that could make us take more time to process and react to the message since the moment it was emitted.

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
