### ISSUE TITLE
When is it safe to release a given scriptId?

### ISSUE THREAD

**Issue by bmeck** [ChromeDevTools/devtools-protocol#95]
I have been unable to tell when it is safe to release a given `scriptId`. We can see when scripts are being generated using `Debugger.scriptParsed` but not when they are being destroyed for whatever reason such as no longer being able to be considered freed for a client to delete.

**Comment by ak239** [comment]
Right now debugger just holds almost all the scripts to allow `Debugger.getScriptContent` call any time in future. We can expose `Debugger.scriptCollected` event and issue this event when script is collected by V8.

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
