### ISSUE TITLE
Attn: Chromium repo source location of browser_protocol.json has changed

### ISSUE THREAD

**Issue by paulirish** [ChromeDevTools/devtools-protocol#96]
Why? [The Great Blink Move](https://groups.google.com/a/chromium.org/d/msg/blink-dev/ysmSWdatQcM/tb6n4ZxhBAAJ).

|  |  |
|---|---|
|Before April 7 2018 | `/src/third_party/WebKit/Source/core/inspector/browser_protocol.json`|
|After April 7 2018 | `/src/third_party/blink/renderer/core/inspector/browser_protocol.json`|

[Git log of `browser_protocol.json`](https://chromium.googlesource.com/chromium/src/+log/master/third_party/blink/renderer/core/inspector/browser_protocol.json).

If you have any scripts which pull the latest, ~a rename of `WebKit/Source/` to `blink/renderer/` will generally do the trick.~ we recommend you [use the JSON offered in this repo](https://github.com/ChromeDevTools/devtools-protocol/tree/master/json) instead.

**Comment by kenshaw** [comment]
@paulirish Do you have any insight into further restructuring / movement plans of the proto definition files in the Chromium tree? I realize this may not be the right place to ask, however they just removed the `browser_protocol.json` from the source:

https://chromium.googlesource.com/chromium/src/+/a42a629f67ac9aae0aaa8fbd912c654559c5d880

Anything you can share would be greatly appreciated! Thanks!

**Comment by ak239** [comment]
We are going to replace all .json protocol definitions files with .pdl ones. .pdl format is designed for protocol definition, contains less noise then .json format and supports multiline comments.
If you still need json file you can use [`convert_protocol_to_json.py`](https://cs.chromium.org/chromium/src/third_party/inspector_protocol/convert_protocol_to_json.py) to generate it from pdl file.

**Comment by paulirish** [comment]
@kenshaw i would recommend pulling the json from https://github.com/ChromeDevTools/devtools-protocol/tree/master/json 
It's maintained and will not change locations.
Also as Aleksey mentions, it's very likely the JSON files will be _removed_ from the chromium repo in the near future.

**Comment by kenshaw** [comment]
@ak239 thanks -- I had seen that code in the commit and assumed that was happening, but just wanted to verify, as the Gerrit issue (at least the public one) doesn't cover anything. I can't seem to find any information on the `pdl` format. Do you have a link to any information? I'm assuming `pdl` is "protocol definition language", but my duckduckgo-fu is not so great.

**Comment by paulirish** [comment]
as of ~5 months ago the PDL files (rather than the json) are the source of truth:

* https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/inspector/browser_protocol.pdl
* https://cs.chromium.org/chromium/src/v8/src/inspector/js_protocol.pdl

this script reads in a .pdl and writes out the .json files: https://cs.chromium.org/chromium/src/third_party/inspector_protocol/convert_protocol_to_json.py

Currently this happens in Chromium at commit-time, but soon that will change and the .json files will no longer be checked into the Chromium repo. So we'll do this conversion here in the `devtools-protocol` repo.

**Comment by paulirish** [comment]
_Update:_

The JSON files have now been removed from the chromium/v8 repos. 

https://github.com/ChromeDevTools/devtools-protocol/tree/master/json is their new home
