### ISSUE TITLE
Feature Request: page.screenshot(dataURL = true)

### ISSUE THREAD

**Issue by F1LT3R** [ChromeDevTools/devtools-protocol#97]
It would be useful to have DataURL passed back as a screenshot, rather than exporting to file.

Example:

```js
const screenshotDataURL = await page.screenshot({
	type: 'png',
	dataURL: true,
})
```

**Comment by aslushnikov** [comment]
@F1LT3R this certainly looks like a puppeteer issue. Can you please re-submit to GoogleChrome/puppeteer?
