### ISSUE TITLE
Debugger not pausing at manual breakpoints when remote debugging

### ISSUE THREAD

**Issue by BrighTide** [ChromeDevTools/devtools-protocol#99]
Chrome: 66.0.3359.139
Local OS: Windows
Remote OS: Linux
Node: Tested with 8.5.0 and 9.7.1

When using node --inspect-brk=0.0.0.0:9229 the debugger is not pausing at breakpoints set manually.
Using the debugger keyword works fine, as does running things locally.

**Comment by eugeneo** [comment]
This is a Node.js issue, please file it to the https://github.com/nodejs/node repository.
